export type CardSet = {
  slug: string;
  name: string;
  sport: 'Soccer' | 'NFL' | 'Basketball' | 'Baseball';
  manufacturer: string;
  year: string;
  difficulty: 'Beginner' | 'Mid Range' | 'Premium';
  status: 'new' | 'coming-soon' | 'current' | 'previous';
  tags: string[];
  shortDescription: string;
  overview: string;
  whatToLookFor: string;
  parallels: { name: string; printRun: string; colour: string }[];
  tips: string[];
  priceRange: string;
  checklistType: 'interactive' | 'pdf' | null;
  checklistUrl?: string;
};

export const cardSets: CardSet[] = [
  // ============================================================
  // SOCCER
  // ============================================================
  {
    slug: 'topps-finest-premier-league-2026',
    name: 'Topps Finest Premier League 2026',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2025-26',
    difficulty: 'Premium',
    status: 'new',
    tags: ['Refractors', 'Autos', 'Premier League', 'New Release'],
    shortDescription: 'Topps Finest comes to the Premier League. Premium refractor based set featuring the biggest names in English football with stunning atomic refractors and on card autographs.',
    overview: 'The historic debut of the Finest brand in the Premier League. Built around a 300-card tiered base set split across Common, Uncommon and Rare tiers, each with their own parallel rainbow. A Hobby-only product featuring two autographs and four to five numbered parallels per box, with big name rookies including Max Dowman, Rio Ngumoha and Estêvão Willian.',
    whatToLookFor: 'Refractor autographs of star players are the top chase. SuperFractor 1/1 autos are the ultimate grail. Finest Idols legends cards and Kaboom-style case hit inserts like Swerve and Main Attraction are the most sought after singles.',
    parallels: [
      { name: 'Sky Blue Refractor', printRun: '/150', colour: 'Sky Blue' },
      { name: 'Purple Refractor', printRun: '/125', colour: 'Purple' },
      { name: 'Blue Refractor', printRun: '/99', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/75', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Orange Refractor', printRun: '/25', colour: 'Orange' },
      { name: 'Black Refractor', printRun: '/10', colour: 'Black' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'SuperFractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Hobby only — no retail version means print runs are more controlled',
      'The tiered base means star players appear three times at different rarity levels — chase the Rare tier',
      'Refractor autos of World Cup-bound players will spike in value this summer',
      'Finest Idols legends inserts are strong long-term holds',
    ],
    priceRange: 'From £5 to £3,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0739/2015/1805/files/Finest_Premier_League_Checklist.pdf?v=1774359572',
  },
  {
    slug: 'donruss-road-to-world-cup',
    name: 'Donruss Road to FIFA World Cup 2026',
    sport: 'Soccer',
    manufacturer: 'Panini',
    year: '2025-26',
    difficulty: 'Mid Range',
    status: 'new',
    tags: ['World Cup', 'Kaboom', 'Rated Rookies'],
    shortDescription: 'The first major international set building towards the 2026 World Cup. Covering 30 national teams with Optic Holo parallels, Kaboom inserts and autographs.',
    overview: 'Panini Donruss Road to FIFA World Cup 2026 is the first major international set building towards the 2026 World Cup in North America. Covering 30 national teams with a 250-card base set including 50 Rated Rookies, it features Optic Holo parallels, Kaboom inserts and autographs from the biggest names in international football.',
    whatToLookFor: 'Kaboom inserts are the headline chase — Gold /10 and Black 1/1 versions of players like Messi, Ronaldo and Lamine Yamal can reach four and five figures. Optic Holo parallels of star players are the most liquid cards in the set.',
    parallels: [
      { name: 'Pink Ice', printRun: 'Unlimited', colour: 'Pink' },
      { name: 'Blue', printRun: '/199', colour: 'Blue' },
      { name: 'Purple', printRun: '/99', colour: 'Purple' },
      { name: 'Red', printRun: '/49', colour: 'Red' },
      { name: 'Gold', printRun: '/10', colour: 'Gold' },
      { name: 'Green', printRun: '/5', colour: 'Green' },
      { name: 'Black', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Kaboom inserts are the must-have chase cards — demand is extremely high',
      'Optic Holo parallels of Messi, Ronaldo and Yamal are the most tradeable cards',
      'World Cup winner cards will spike massively in value after the tournament',
      'Rated Rookies of breakout World Cup stars could be huge long-term holds',
    ],
    priceRange: 'From £2 to £5,000+',
    checklistType: 'interactive',
  },
  {
    slug: 'topps-chrome-ucc-2526',
    name: 'Topps Chrome UCC 2025-26',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2025-26',
    difficulty: 'Premium',
    status: 'new',
    tags: ['Chrome', 'UCL', 'Europa', 'New Release'],
    shortDescription: 'UCC Chrome is back. The premium chrome set covering UEFA Club Competitions including the Champions League, Europa League and Conference League.',
    overview: 'UCC Chrome is back. Topps Chrome returns to UEFA Club Competitions for the 2025-26 season covering the Champions League, Europa League and Conference League. The premium chrome treatment brings refractor parallels and autographs of Europe\'s best players in what is set to be one of the most anticipated football card releases of the year.',
    whatToLookFor: 'Chrome refractors of Champions League stars are the top chase cards. Autographed refractors of European elite players will command strong premiums. Look for rookie chrome cards of breakout players from the 2025-26 season.',
    parallels: [
      { name: 'Base Chrome', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/99', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Orange Refractor', printRun: '/25', colour: 'Orange' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'UCC Chrome has a passionate collector base — demand at launch will be strong',
      'Champions League winners cards always spike in value after the final',
      'Buy cards of players before the knockout rounds when prices are still reasonable',
      'Europa and Conference League player cards are often undervalued compared to UCL equivalents',
    ],
    priceRange: 'From £5 to £3,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/26TUCC_ChromeChecklist_FINAL.pdf?v=1775059905',
  },
  {
    slug: 'merlin-premier-league',
    name: 'Merlin Premier League',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2018-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Refractors', 'Autos', 'Rookie Cards'],
    shortDescription: 'The nostalgia of the 90s with bold Chrome finishes and wizardry-inspired design.',
    overview: 'Blending the nostalgia of the 90s with bold Chrome finishes and wizardry-inspired design, this release celebrates the game\'s past, present, and future through a truly unique artistic lens.',
    whatToLookFor: 'Collectors can chase a vibrant array of parallels, including the nostalgic VHS Refractor and the limited Battle of Britpop Refractor, limited to 95 copies. Short-printed variations such as the Merlin Premier League 1996 throwback design.',
    parallels: [
      { name: 'Base Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'VHS Refractor', printRun: 'Limited', colour: 'Various' },
      { name: 'Battle of Britpop Refractor', printRun: '/95', colour: 'Various' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'SuperFractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Look for select gold pen on-card autograph cards — the rarest auto pulls in the set',
      'VHS Refractors lean heavily on 90s nostalgia and are popular with older collectors',
      'Battle of Britpop Refractor at /95 is one of the more genuinely rare parallels',
      'Strong UK collector demand given the Premier League focus',
    ],
    priceRange: 'From £5 to £2,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0739/2015/1805/files/Merlin_Premier_League_2026_Hobby_Box_Checklist_1.pdf?v=1777382734',
  },
  {
    slug: 'topps-chrome',
    name: 'Topps Chrome',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2019-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Refractors', 'Autos', 'Rookie Cards'],
    shortDescription: 'The most prestigious football card set in the hobby. Known for its iconic chromium finish and highly sought after autographs and refractors.',
    overview: 'Topps Chrome is widely considered the most prestigious football card set in the modern hobby. Built on a chromium card stock that gives each card a distinctive shine and durability, Chrome has become the benchmark by which all other football sets are measured.',
    whatToLookFor: 'Rookie Cards of players in their first professional season are the most valuable. Autograph cards signed directly on the card carry a significant premium. Refractors come in various colours with different print runs, with Gold (/50), Orange (/25) and Red (/5) being the rarest.',
    parallels: [
      { name: 'Base Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/99', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Orange Refractor', printRun: '/25', colour: 'Orange' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Always check the print run - lower numbers mean higher value',
      'Graded copies (PSA/BGS) of top rookies command a significant premium',
      'Look for on-card autos rather than sticker autos - they are worth more',
      'Bellingham, Palmer and Saka rookies are the most sought after UK players',
    ],
    priceRange: 'From £5 to £5,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0739/2015/1805/files/FINAL_PL_Chrome_Checklist.pdf?v=1770285570',
  },
  {
    slug: 'panini-prizm-epl',
    name: 'Panini Prizm EPL',
    sport: 'Soccer',
    manufacturer: 'Panini',
    year: '2019-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Prizms', 'Silver', 'Parallels'],
    shortDescription: 'Panini\'s flagship Premier League set. Famous for its Silver Prizm parallels and coloured refractors.',
    overview: 'Panini Prizm EPL is the Premier League equivalent of Topps Chrome. Covering all 20 Premier League clubs, Prizm EPL features the biggest names in English football and its Silver Prizm parallel has become one of the most recognisable cards in the hobby.',
    whatToLookFor: 'Silver Prizms of star players are the bread and butter of this set. Autographed Prizms are extremely valuable. The Wave Prizm parallel is one of the most visually striking cards in the hobby.',
    parallels: [
      { name: 'Silver Prizm', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Prizm', printRun: '/199', colour: 'Blue' },
      { name: 'Green Prizm', printRun: '/99', colour: 'Green' },
      { name: 'Purple Prizm', printRun: '/49', colour: 'Purple' },
      { name: 'Gold Prizm', printRun: '/10', colour: 'Gold' },
      { name: 'Black Prizm', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Silver Prizms are the most liquid - easiest to buy and sell',
      'Wave Prizms have a unique pattern and are very popular with collectors',
      'EPL Prizm holds value well due to worldwide demand for Premier League cards',
      'Look for short print variations which are harder to find in packs',
    ],
    priceRange: 'From £3 to £2,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/2024-25-panini-prizm-premier-league-soccer-cards/',
  },
  {
    slug: 'topps-stadium-club',
    name: 'Topps Stadium Club',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2021-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Photography', 'Clean Design', 'Autos'],
    shortDescription: 'Known for its stunning photography and clean design. A favourite among collectors who appreciate artistry.',
    overview: 'Topps Stadium Club Chrome is known for its stunning photography and clean artistic design. Unlike refractor heavy Chrome sets, Stadium Club puts photography front and centre making each card feel more like a piece of art than a trading card.',
    whatToLookFor: 'Black and White parallel cards are visually striking and popular. Autograph cards feature on-card signatures. Co-signers featuring multiple player autographs on one card are rare and valuable.',
    parallels: [
      { name: 'Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Black and White', printRun: '/99', colour: 'Monochrome' },
      { name: 'Gold', printRun: '/50', colour: 'Gold' },
      { name: 'Red', printRun: '/5', colour: 'Red' },
      { name: '1/1', printRun: '1/1', colour: 'Various' },
    ],
    tips: [
      'Base cards are genuinely beautiful - worth collecting for the photography alone',
      'Black and White parallels are the most popular and visually striking',
      'A great mid-range set for collectors who want quality without Chrome prices',
      'Stadium Club has a loyal community - easy to buy and sell within hobby groups',
    ],
    priceRange: 'From £2 to £500+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/topps-stadium-club-chrome-soccer/',
  },
  {
    slug: 'panini-select',
    name: 'Panini Select',
    sport: 'Soccer',
    manufacturer: 'Panini',
    year: '2020-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Tiered', 'Parallels', 'Rookies'],
    shortDescription: 'Three tier design featuring Concourse, Premier and Courtside levels with bold colourful parallels.',
    overview: 'Panini Select is one of the most visually distinctive sets in the football card hobby. Its three tier design featuring Concourse, Premier and Courtside levels gives collectors different card designs within the same product.',
    whatToLookFor: 'Courtside die cut cards are the most distinctive and sought after. Tri-Colour parallels are among the most visually striking cards in the hobby. Look for numbered parallels of top Premier League players.',
    parallels: [
      { name: 'Concourse Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Premier Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Courtside', printRun: 'Limited', colour: 'Die Cut' },
      { name: 'Tri-Colour', printRun: '/49', colour: 'Multi' },
      { name: 'Gold', printRun: '/10', colour: 'Gold' },
      { name: 'Black', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Courtside cards are the ones to chase - the die cut design is unlike anything else',
      'Tri-Colour parallels are incredibly popular and very eye catching',
      'Select boxes offer good value compared to Chrome at similar price points',
      'The three tier system means more variety - something for every collector',
    ],
    priceRange: 'From £2 to £1,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/panini-select-soccer/',
  },
  {
    slug: 'topps-chrome-sapphire',
    name: 'Topps Chrome Sapphire',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2018-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Sapphire', 'Limited', 'Ultra Premium'],
    shortDescription: 'The ultra premium edition of Topps Chrome. Limited print run with stunning sapphire blue refractor finish.',
    overview: 'Topps Chrome Sapphire is the ultra premium edition of Topps Chrome. Released exclusively through the Topps website and selected retailers, Sapphire features a stunning blue refractor finish on every card making the entire base set refractors. With a significantly limited print run compared to standard Chrome, Sapphire cards command a substantial premium and are among the most desirable cards in the modern hobby.',
    whatToLookFor: 'Every base card in Sapphire is a refractor making them all more valuable than standard Chrome base. Autographed Sapphire cards are extremely rare and valuable. Parallel versions including Gold and SuperFractor are the ultimate chase cards. Rookie Sapphires of top players can be worth many times their standard Chrome equivalent.',
    parallels: [
      { name: 'Base Sapphire Refractor', printRun: 'Limited', colour: 'Blue' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Orange Refractor', printRun: '/25', colour: 'Orange' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'SuperFractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Every base card is a refractor - making even base cards significantly more valuable than standard Chrome',
      'Sapphire sells out fast - pre-order if possible when new editions are announced',
      'PSA graded Sapphire rookies of top players hold value exceptionally well',
      'Compare prices carefully - Sapphire premiums can be 5-10x standard Chrome prices',
    ],
    priceRange: 'From £20 to £5,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0739/2015/1805/files/CheckList_26PLCM_Sapphire_Completed.pdf?v=1772811316',
  },
  {
    slug: 'topps-now',
    name: 'Topps NOW',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2017-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Limited Edition', 'Event Cards', 'Rare'],
    shortDescription: 'Limited edition cards released within 24-48 hours of major football moments. Print to order with very limited windows.',
    overview: 'Topps NOW is unlike any other card product. Cards are released within 24-48 hours of significant football moments - a hat trick, a title win, a record breaking performance. Cards are only available for a limited 24-48 hour window making them genuinely rare. The print run is determined by how many are ordered during that window.',
    whatToLookFor: 'Cards commemorating historic moments are the most valuable - title winning goals, record breaking performances, debut cards. Low print run cards from less popular windows can be very scarce. Look for moments that will be remembered long term as those cards appreciate most.',
    parallels: [
      { name: 'Base Card', printRun: 'Print to Order', colour: 'Standard' },
      { name: 'Blue Parallel', printRun: '/10', colour: 'Blue' },
      { name: 'Gold Parallel', printRun: '/5', colour: 'Gold' },
      { name: '1/1', printRun: '1/1', colour: 'Various' },
    ],
    tips: [
      'Order during the window - once it closes you can only buy on the secondary market at a premium',
      'Historic moments create the most valuable cards - title clinchers, records, debuts',
      'Low ordered print runs can make even base cards genuinely rare',
      'Follow Topps social media to never miss a new release window',
    ],
    priceRange: 'From £5 to £500+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.topps.com/pages/topps-now',
  },
  {
    slug: 'topps-inception',
    name: 'Topps Inception',
    sport: 'Soccer',
    manufacturer: 'Topps',
    year: '2019-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Autos', 'Acetate', 'On Card'],
    shortDescription: 'Premium on card autograph focused set with stunning acetate cards. Every box guaranteed to contain autographs.',
    overview: 'Topps Inception is built around on card autographs on stunning acetate card stock. The see-through acetate design makes Inception cards unlike anything else in the hobby. Every hobby box is guaranteed to contain autographs making it a popular choice for collectors who want to pull signatures from top players.',
    whatToLookFor: 'On card acetate autographs are the signature cards of this set. Rookie autographs are the most valuable. The see-through acetate design makes every card a standout piece. Look for parallel versions of autograph cards for the rarest pulls.',
    parallels: [
      { name: 'Base Acetate', printRun: 'Unlimited', colour: 'Clear' },
      { name: 'Blue Parallel', printRun: '/150', colour: 'Blue' },
      { name: 'Gold Parallel', printRun: '/50', colour: 'Gold' },
      { name: 'Red Parallel', printRun: '/5', colour: 'Red' },
      { name: 'SuperFractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'The acetate design is unique in the hobby - makes for stunning display pieces',
      'On card autos are guaranteed in hobby boxes making it great value for auto hunters',
      'Rookie acetate autos of top players are among the most desirable cards in the set',
      'Store carefully - acetate cards can scratch more easily than standard card stock',
    ],
    priceRange: 'From £5 to £3,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/topps-inception-soccer/',
  },

  // ============================================================
  // NFL
  // ============================================================
  {
    slug: 'topps-nfl',
    name: 'Topps NFL',
    sport: 'NFL',
    manufacturer: 'Topps',
    year: '2025',
    difficulty: 'Premium',
    status: 'coming-soon',
    tags: ['Chrome', 'Rookies', 'Topps Comeback'],
    shortDescription: 'Topps returns to NFL trading cards for the first time in over a decade. Highly anticipated comeback.',
    overview: 'Topps returns to NFL trading cards for the first time in over a decade. The highly anticipated comeback brings Topps Chrome quality to American football, featuring rookie cards and autographs of the biggest names in the NFL. One of the most talked about product launches in the hobby for years.',
    whatToLookFor: 'Rookie Chrome refractors of top draft picks especially quarterbacks are the biggest chase cards. Autographed refractors will command significant premiums. Look for numbered parallels of established stars and breakout players early before prices rise.',
    parallels: [
      { name: 'Base Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/99', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Orange Refractor', printRun: '/25', colour: 'Orange' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Topps returning to NFL is massive news — expect strong demand and premium prices at launch',
      'Quarterback rookie refractors will be the most valuable cards in the set',
      'Buy early before the hobby catches on — launch prices often represent the best value',
      'Compare carefully with Panini Prizm NFL to understand relative values',
    ],
    priceRange: 'TBC — launching 2025',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/2025_Chrome_Football_Checklist_040826.pdf?v=1775678965',
  },
  {
    slug: 'panini-prizm-nfl',
    name: 'Panini Prizm NFL',
    sport: 'NFL',
    manufacturer: 'Panini',
    year: '2012-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Prizms', 'Rookies', 'NFL'],
    shortDescription: 'The most popular NFL card set. Rookie Prizms of top draft picks are among the most valuable cards in the hobby.',
    overview: 'Panini Prizm NFL is the most popular American football card set in the hobby. Rookie Prizms of top NFL draft picks are among the most traded cards in the entire sports card market. With the NFL being the most watched sport in America, demand for Prizm cards is enormous.',
    whatToLookFor: 'Rookie Prizms of first round draft picks especially quarterbacks are the biggest chase cards. Silver Prizms are the most liquid and easiest to trade. Look for numbered parallels of star players and Super Bowl winners for maximum value.',
    parallels: [
      { name: 'Silver Prizm', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Prizm', printRun: '/199', colour: 'Blue' },
      { name: 'Green Prizm', printRun: '/99', colour: 'Green' },
      { name: 'Purple Prizm', printRun: '/49', colour: 'Purple' },
      { name: 'Gold Prizm', printRun: '/10', colour: 'Gold' },
      { name: 'Black Prizm', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Quarterback rookie Prizms are always the most valuable in any given year',
      'Buy rookie Prizms early in the season before prices rise after breakout performances',
      'The US market for NFL cards is massive - excellent liquidity',
      'Super Bowl performance can dramatically increase a player\'s card values overnight',
    ],
    priceRange: 'From £3 to £15,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/panini-prizm-football/',
  },
  {
    slug: 'topps-chrome-nfl',
    name: 'Topps Cosmic Chrome NFL',
    sport: 'NFL',
    manufacturer: 'Topps',
    year: '1996-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Chrome', 'Rookies', 'QBs'],
    shortDescription: 'A classic chromium NFL set with strong collector demand. Rookie cards of star quarterbacks are particularly valuable.',
    overview: 'Topps Chrome NFL has a rich history in the American football card hobby. The chromium finish gives each card a premium feel and rookie cards from key years are highly collectible. A strong alternative to Prizm with a loyal collector base.',
    whatToLookFor: 'Rookie refractors of star quarterbacks are the most valuable cards. Vintage Chrome NFL cards from the late 1990s featuring early career cards of legends are worth seeking out. Autographed refractors command strong premiums.',
    parallels: [
      { name: 'Base Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/99', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Chrome NFL offers good value compared to Prizm at similar price points',
      'Early career Chrome cards of NFL legends are seriously undervalued',
      'Quarterback refractors are always the most sought after position',
      'Graded copies of star rookie refractors hold value very well',
    ],
    priceRange: 'From £2 to £5,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/NFL2405-2024ToppsCosmicChromeChecklist_V2.pdf?v=1744134769',
  },
  {
    slug: 'panini-select-nfl',
    name: 'Panini Select NFL',
    sport: 'NFL',
    manufacturer: 'Panini',
    year: '2018-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Tiered', 'Parallels', 'Bold'],
    shortDescription: 'Three tier design with bold colourful parallels. One of the most visually striking NFL sets available.',
    overview: 'Panini Select NFL brings the distinctive three tier design to American football. The bold colourful parallels and die cut Courtside cards make this one of the most visually striking NFL sets available. A favourite among collectors who want something different from Prizm.',
    whatToLookFor: 'Courtside die cut cards are the standout cards from this set. Tri-Colour parallels of star quarterbacks and wide receivers are particularly popular. Rookie Courtside cards of top draft picks can be very valuable.',
    parallels: [
      { name: 'Concourse Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Premier Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Courtside', printRun: 'Limited', colour: 'Die Cut' },
      { name: 'Tri-Colour', printRun: '/49', colour: 'Multi' },
      { name: 'Gold', printRun: '/10', colour: 'Gold' },
      { name: 'Black', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Courtside rookie cards of quarterbacks are the top chase cards in this set',
      'Select offers great visual variety compared to standard Prizm',
      'Tri-Colour parallels are extremely popular and very eye catching',
      'Good value boxes compared to Prizm with similar hit rates',
    ],
    priceRange: 'From £2 to £3,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/panini-select-football/',
  },

  // ============================================================
  // BASKETBALL
  // ============================================================
  {
    slug: 'panini-prizm-nba',
    name: 'Panini Prizm NBA',
    sport: 'Basketball',
    manufacturer: 'Panini',
    year: '2012-2025',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Prizms', 'Silver', 'NBA'],
    shortDescription: 'The gold standard of basketball cards. Silver Prizms of top NBA players are among the most traded cards in the hobby worldwide.',
    overview: 'Panini Prizm NBA is the gold standard of basketball cards. Launched in 2012, it quickly became the most popular and traded basketball card set in the world. Silver Prizms of top NBA players are instantly recognisable and form the backbone of the modern basketball card market.',
    whatToLookFor: 'Silver Prizms of star players and top rookies are the most liquid cards in the hobby. Rookie Prizms of first round draft picks can be extremely valuable especially if the player has a breakout season. Look for numbered parallels and on-card autographs for maximum value.',
    parallels: [
      { name: 'Silver Prizm', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Prizm', printRun: '/199', colour: 'Blue' },
      { name: 'Green Prizm', printRun: '/99', colour: 'Green' },
      { name: 'Purple Prizm', printRun: '/49', colour: 'Purple' },
      { name: 'Gold Prizm', printRun: '/10', colour: 'Gold' },
      { name: 'Black Prizm', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Silver Prizms are the most traded cards in basketball - very easy to buy and sell',
      'Rookie Prizms of lottery picks are worth grabbing early before prices rise',
      'PSA 10 graded Silver Prizms of star players command a massive premium',
      'Look for short print variations and rare colour parallels for the biggest returns',
    ],
    priceRange: 'From £3 to £10,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/panini-prizm-basketball/',
  },
  {
    slug: 'topps-chrome-nba',
    name: 'Topps Chrome Basketball',
    sport: 'Basketball',
    manufacturer: 'Topps',
    year: '1996-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Chrome', 'Rookies', 'Classic'],
    shortDescription: 'A classic chromium basketball set with a long history. Rookie cards from this set are highly collectible.',
    overview: 'Topps Chrome NBA has a long and storied history dating back to 1996. One of the earliest chromium basketball sets, it has produced some of the most iconic rookie cards in the hobby including early Kobe Bryant and LeBron James cards which are among the most valuable sports cards ever made.',
    whatToLookFor: 'Vintage Chrome rookie cards from the late 1990s and early 2000s are the real prizes. Modern releases focus on current NBA stars and rookies. Refractor parallels are the most sought after within the set.',
    parallels: [
      { name: 'Base Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/99', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Vintage Topps Chrome rookies from the late 90s are seriously undervalued',
      'Look for early LeBron and Kobe Chrome cards for the biggest long term returns',
      'Modern Chrome NBA offers good value compared to Prizm at similar price points',
      'Graded copies of star rookie cards hold value extremely well',
    ],
    priceRange: 'From £2 to £50,000+ (vintage)',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0739/2015/1805/files/2025-26_Topps_Chrome_Basketball_Checklist_1.pdf?v=1766053015',
  },
  {
    slug: 'panini-select-nba',
    name: 'Panini Select NBA',
    sport: 'Basketball',
    manufacturer: 'Panini',
    year: '2014-2025',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Tiered', 'Die Cut', 'Parallels'],
    shortDescription: 'Three tier design with Concourse, Premier and Courtside levels. Die cut Courtside cards are the most sought after.',
    overview: 'Panini Select NBA features the distinctive three tier design of Concourse, Premier and Courtside levels. The die cut Courtside cards are the standout feature of this set and have become one of the most recognisable card designs in the hobby.',
    whatToLookFor: 'Courtside die cut cards are the must have cards from this set. Tri-Colour parallels are visually striking and popular with collectors. Rookie cards of top draft picks in the Courtside design are particularly valuable.',
    parallels: [
      { name: 'Concourse Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Premier Base', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Courtside', printRun: 'Limited', colour: 'Die Cut' },
      { name: 'Tri-Colour', printRun: '/49', colour: 'Multi' },
      { name: 'Gold', printRun: '/10', colour: 'Gold' },
      { name: 'Black', printRun: '1/1', colour: 'Black' },
    ],
    tips: [
      'Courtside cards are the ones to chase - the die cut design is iconic',
      'Select boxes offer great variety with three different card designs per box',
      'Tri-Colour parallels are very popular and photograph beautifully',
      'A good alternative to Prizm if you want something visually different',
    ],
    priceRange: 'From £2 to £2,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://www.beckett.com/news/panini-select-basketball/',
  },

  // ============================================================
  // BASEBALL
  // ============================================================
  {
    slug: 'topps-chrome-baseball',
    name: 'Topps Chrome Baseball',
    sport: 'Baseball',
    manufacturer: 'Topps',
    year: '1996-Present',
    difficulty: 'Premium',
    status: 'current',
    tags: ['Chrome', 'Rookies', 'MLB'],
    shortDescription: 'The original Chrome set and still one of the most popular. Rookie cards of MLB stars are the most valuable.',
    overview: 'Topps Chrome Baseball is the premier modern baseball card set. The chromium finish elevates the classic Topps design and rookie cards from this set are among the most valuable in the baseball card hobby. A staple product that every serious baseball card collector follows closely.',
    whatToLookFor: 'Rookie cards of top MLB prospects are the biggest chase cards. Autographed refractors are extremely valuable. Look for short print variations and rare parallels of star players for maximum returns.',
    parallels: [
      { name: 'Base Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Green Refractor', printRun: '/99', colour: 'Green' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Orange Refractor', printRun: '/25', colour: 'Orange' },
      { name: 'Red Refractor', printRun: '/5', colour: 'Red' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Follow MLB prospect rankings closely - early Chrome rookies of future stars are gold',
      'Autographed refractors of top prospects can skyrocket in value quickly',
      'The US baseball card market is massive - liquidity is excellent',
      'Short print variations are harder to find and worth a significant premium',
    ],
    priceRange: 'From £3 to £20,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/MLB2501-2025ToppsSeries1BBChecklistV3_b89e7210-e09d-41d9-84d1-d51a34abcadf.pdf?v=1739307106',
  },
  {
    slug: 'topps-baseball',
    name: 'Topps Heritage Baseball',
    sport: 'Baseball',
    manufacturer: 'Topps',
    year: '1952-Present',
    difficulty: 'Beginner',
    status: 'current',
    tags: ['Classic', 'Heritage', 'Iconic'],
    shortDescription: 'The most iconic baseball card set in history. Heritage Topps cards from 1977 set design are among the most valuable sports cards ever.',
    overview: 'Topps Baseball is the most iconic trading card set in history. Dating back to 1952, it has documented every era of Major League Baseball for over 70 years. Vintage Topps cards from the 1950s to 1970s featuring legends like Mickey Mantle and Babe Ruth are among the most valuable sports cards ever sold.',
    whatToLookFor: 'Vintage cards from the 1950s-1970s in good condition are the most valuable. The 1952 Topps Mickey Mantle is one of the most famous cards in existence. Modern Topps Series 1 and 2 offer affordable collecting with short prints and autographs worth chasing.',
    parallels: [
      { name: 'Base Card', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Gold Parallel', printRun: '/2025', colour: 'Gold' },
      { name: 'Black Parallel', printRun: '/63', colour: 'Black' },
      { name: 'Platinum', printRun: '1/1', colour: 'Platinum' },
    ],
    tips: [
      'Vintage Topps cards in PSA graded condition are serious investments',
      'Check car boot sales and charity shops for hidden vintage treasures',
      'Modern Topps is very affordable and great for new collectors',
      'Short print variations in modern sets are worth looking out for',
    ],
    priceRange: 'From £0.10 to £1,000,000+ (vintage)',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/Checklist_26THBB_3.20.pdf?v=1774362662',
  },
  {
    slug: 'bowman-baseball',
    name: 'Bowman Baseball',
    sport: 'Baseball',
    manufacturer: 'Topps',
    year: '1948-Present',
    difficulty: 'Mid Range',
    status: 'current',
    tags: ['Prospects', 'Rookies', 'First Cards'],
    shortDescription: 'The go-to set for prospect collectors. First Bowman cards of players who make the major leagues can be extremely valuable.',
    overview: 'Bowman Baseball is the definitive prospect set. Collectors chase First Bowman cards of top MLB prospects years before they reach the major leagues. When a prospect becomes a star, their First Bowman card can increase dramatically in value making this one of the most exciting sets to collect.',
    whatToLookFor: 'First Bowman cards of top prospects are the most important cards in the set. Bowman Chrome versions of prospect cards are more valuable than the base paper versions. Autographed prospect cards are the ultimate chase cards in this set.',
    parallels: [
      { name: 'Base Paper', printRun: 'Unlimited', colour: 'Standard' },
      { name: 'Chrome Base', printRun: 'Unlimited', colour: 'Chrome' },
      { name: 'Chrome Refractor', printRun: 'Unlimited', colour: 'Silver' },
      { name: 'Blue Refractor', printRun: '/150', colour: 'Blue' },
      { name: 'Gold Refractor', printRun: '/50', colour: 'Gold' },
      { name: 'Superfractor', printRun: '1/1', colour: 'Gold' },
    ],
    tips: [
      'Follow Baseball America prospect rankings to know which players to target',
      'First Bowman Chrome autos of top prospects are the biggest long term investments',
      'Buy prospect cards before they debut in the majors for the best prices',
      'Graded First Bowman cards hold value extremely well long term',
    ],
    priceRange: 'From £1 to £50,000+',
    checklistType: 'pdf',
    checklistUrl: 'https://cdn.shopify.com/s/files/1/0662/9749/5709/files/MLB2507-2025BowmanBaseballChecklist2.pdf?v=1746543006',
  },
];

// Helper functions for the pages to use

export function getSetBySlug(slug: string): CardSet | undefined {
  return cardSets.find(s => s.slug === slug);
}

export function getSetsBySport(sport: CardSet['sport']): CardSet[] {
  return cardSets.filter(s => s.sport === sport);
}

export function getSportsList(): CardSet['sport'][] {
  return Array.from(new Set(cardSets.map(s => s.sport)));
}

export function getSetsByStatus(status: CardSet['status']): CardSet[] {
  return cardSets.filter(s => s.status === status);
}

export function getChecklistHref(set: CardSet): string | null {
  if (set.checklistType === 'interactive') return `/sets/${set.slug}/checklist`;
  if (set.checklistType === 'pdf' && set.checklistUrl) return set.checklistUrl;
  return null;
}