import type { Checklist } from './index';

export const merlinPremierLeague2026: Checklist = {
  setSlug: 'merlin-premier-league',
  setName: 'Topps Merlin Premier League 2026',
  setBadge: '🔮 Out Now',
  setSubtitle: 'Topps · 2025-26 · Full Checklist',
  ebaySearchSuffix: 'Topps Merlin Premier League 2026',
  filterDimension: {
    field: 'team',
    label: 'Team',
    placeholder: 'All Teams',
  },
  sectionColors: {
    'Base Cards': '#1F6F3A',
    'Fantasy Football': '#1F6F3A',
    'Mystic Afternoons': '#f59e0b',
    "Merlin's Young Magicians": '#1F6F3A',
    'Merlin Speaks': '#1F6F3A',
    'Ta-Da': '#1F6F3A',
    "Merlin's Mythical Art": '#f59e0b',
    'Rainbow Flick': '#1F6F3A',
    'Merlin Premier League 1996 Edition': '#f59e0b',
    'Magic In His Boots': '#1F6F3A',
    'The Shiny': '#f59e0b',
    'Renaissance': '#1F6F3A',
    "Merlin's Magnum Opus": '#f59e0b',
    'Mask Off': '#f59e0b',
    'Autograph Variations': '#1F6F3A',
    'Mystic Afternoons Autographs': '#f59e0b',
    'Enchanted Pen': '#1F6F3A',
    'Spellbinding Trios': '#1F6F3A',
    "Merlin's Magical Ink": '#1F6F3A',
    "Merlin's Match Ball Signatures": '#f59e0b',
  },
  sections: {
    'Base Cards': [
      { num: 1, name: 'Alex Scott', team: 'AFC Bournemouth' },
      { num: 2, name: 'Marcos Senesi', team: 'AFC Bournemouth' },
      { num: 3, name: 'Marcus Tavernier', team: 'AFC Bournemouth' },
      { num: 4, name: 'Julio Soler', team: 'AFC Bournemouth', isRookie: true },
      { num: 5, name: 'Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 6, name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 7, name: 'Adrien Truffert', team: 'AFC Bournemouth' },
      { num: 8, name: 'Amine Adli', team: 'AFC Bournemouth' },
      { num: 9, name: 'Veljko Milosavljević', team: 'AFC Bournemouth', isRookie: true },
      { num: 10, name: 'Bafodé Diakité', team: 'AFC Bournemouth' },
      { num: 11, name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 12, name: 'Viktor Gyökeres', team: 'Arsenal' },
      { num: 13, name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 14, name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 15, name: 'Noni Madueke', team: 'Arsenal' },
      { num: 16, name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 17, name: 'Mikel Merino', team: 'Arsenal' },
      { num: 18, name: 'Andre Harriman-Annous', team: 'Arsenal', isRookie: true },
      { num: 19, name: 'Josh Nichols', team: 'Arsenal', isRookie: true },
      { num: 20, name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 21, name: 'Ian Maatsen', team: 'Aston Villa' },
      { num: 22, name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 23, name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 24, name: 'Amadou Onana', team: 'Aston Villa' },
      { num: 25, name: 'Youri Tielemans', team: 'Aston Villa' },
      { num: 26, name: 'Bradley Burrowes', team: 'Aston Villa', isRookie: true },
      { num: 27, name: 'Jamaldeen Jimoh-Aloba', team: 'Aston Villa', isRookie: true },
      { num: 28, name: 'Matty Cash', team: 'Aston Villa' },
      { num: 29, name: 'Lamare Bogarde', team: 'Aston Villa' },
      { num: 30, name: 'Boubacar Kamara', team: 'Aston Villa' },
      { num: 31, name: 'Mathias Jensen', team: 'Brentford' },
      { num: 32, name: 'Mikkel Damsgaard', team: 'Brentford' },
      { num: 33, name: 'Kevin Schade', team: 'Brentford' },
      { num: 34, name: 'Dango Ouattara', team: 'Brentford' },
      { num: 35, name: 'Igor Thiago', team: 'Brentford' },
      { num: 36, name: 'Jordan Henderson', team: 'Brentford' },
      { num: 37, name: 'Michael Kayode', team: 'Brentford' },
      { num: 38, name: 'Caoimhín Kelleher', team: 'Brentford' },
      { num: 39, name: 'Nathan Collins', team: 'Brentford' },
      { num: 40, name: 'Yehor Yarmolyuk', team: 'Brentford' },
      { num: 41, name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 42, name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 43, name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 44, name: 'Yankuba Minteh', team: 'Brighton & Hove Albion' },
      { num: 45, name: 'Diego Gómez', team: 'Brighton & Hove Albion' },
      { num: 46, name: 'Lewis Dunk', team: 'Brighton & Hove Albion' },
      { num: 47, name: 'Jan Paul van Hecke', team: 'Brighton & Hove Albion' },
      { num: 48, name: 'Ferdi Kadioglu', team: 'Brighton & Hove Albion' },
      { num: 49, name: 'Harry Howell', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 50, name: 'Stefanos Tzimas', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 51, name: 'Jaidon Anthony', team: 'Burnley FC' },
      { num: 52, name: 'Marcus Edwards', team: 'Burnley FC' },
      { num: 53, name: 'Kyle Walker', team: 'Burnley FC' },
      { num: 54, name: 'Josh Laurent', team: 'Burnley FC', isRookie: true },
      { num: 55, name: 'Florentino Luís', team: 'Burnley FC' },
      { num: 56, name: 'Martin Dúbravka', team: 'Burnley FC' },
      { num: 57, name: 'Quilindschy Hartman', team: 'Burnley FC' },
      { num: 58, name: 'Jacob Bruun Larsen', team: 'Burnley FC' },
      { num: 59, name: 'Lyle Foster', team: 'Burnley FC' },
      { num: 60, name: 'Josh Cullen', team: 'Burnley FC' },
      { num: 61, name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 62, name: 'Reece James', team: 'Chelsea' },
      { num: 63, name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 64, name: 'Roméo Lavia', team: 'Chelsea' },
      { num: 65, name: 'João Pedro', team: 'Chelsea' },
      { num: 66, name: 'Liam Delap', team: 'Chelsea' },
      { num: 67, name: 'Cole Palmer', team: 'Chelsea' },
      { num: 68, name: 'Josh Acheampong', team: 'Chelsea' },
      { num: 69, name: 'Marc Cucurella', team: 'Chelsea' },
      { num: 70, name: 'Alejandro Garnacho', team: 'Chelsea' },
      { num: 71, name: 'Daniel Muñoz', team: 'Crystal Palace' },
      { num: 72, name: 'Daichi Kamada', team: 'Crystal Palace' },
      { num: 73, name: 'Justin Devenny', team: 'Crystal Palace', isRookie: true },
      { num: 74, name: 'Yéremy Pino', team: 'Crystal Palace' },
      { num: 75, name: 'Ismaïla Sarr', team: 'Crystal Palace' },
      { num: 76, name: 'Joél Drakes-Thomas', team: 'Crystal Palace', isRookie: true },
      { num: 77, name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 78, name: 'Jaydee Canvot', team: 'Crystal Palace', isRookie: true },
      { num: 79, name: 'Tyrick Mitchell', team: 'Crystal Palace' },
      { num: 80, name: 'Jefferson Lerma', team: 'Crystal Palace' },
      { num: 81, name: 'Merlin Röhl', team: 'Everton' },
      { num: 82, name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 83, name: 'Jack Grealish', team: 'Everton' },
      { num: 84, name: 'Tyler Dibling', team: 'Everton' },
      { num: 85, name: 'Tim Iroegbunam', team: 'Everton' },
      { num: 86, name: 'Kiernan Dewsbury-Hall', team: 'Everton' },
      { num: 87, name: "Jake O'Brien", team: 'Everton' },
      { num: 88, name: 'Idrissa Gueye', team: 'Everton' },
      { num: 89, name: 'Jordan Pickford', team: 'Everton' },
      { num: 90, name: 'Vitalii Mykolenko', team: 'Everton' },
      { num: 91, name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 92, name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 93, name: 'Harry Wilson', team: 'Fulham' },
      { num: 94, name: 'Jonah Kusi-Asare', team: 'Fulham', isRookie: true },
      { num: 95, name: 'Kevin', team: 'Fulham' },
      { num: 96, name: 'Calvin Bassey', team: 'Fulham' },
      { num: 97, name: 'Ryan Sessegnon', team: 'Fulham' },
      { num: 98, name: 'Sander Berge', team: 'Fulham' },
      { num: 99, name: 'Joachim Andersen', team: 'Fulham' },
      { num: 100, name: 'Saša Lukić', team: 'Fulham' },
      { num: 101, name: 'Dominic Calvert-Lewin', team: 'Leeds United' },
      { num: 102, name: 'Ethan Ampadu', team: 'Leeds United' },
      { num: 103, name: 'Gabriel Gudmundsson', team: 'Leeds United' },
      { num: 104, name: 'Ao Tanaka', team: 'Leeds United' },
      { num: 105, name: 'Sean Longstaff', team: 'Leeds United' },
      { num: 106, name: 'Daniel James', team: 'Leeds United' },
      { num: 107, name: 'Lukas Nmecha', team: 'Leeds United' },
      { num: 108, name: 'Jayden Bogle', team: 'Leeds United' },
      { num: 109, name: 'Wilfried Gnonto', team: 'Leeds United' },
      { num: 110, name: 'Anton Stach', team: 'Leeds United' },
      { num: 111, name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 112, name: 'Federico Chiesa', team: 'Liverpool FC' },
      { num: 113, name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 114, name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 115, name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 116, name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 117, name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 118, name: 'Cody Gakpo', team: 'Liverpool FC' },
      { num: 119, name: 'Conor Bradley', team: 'Liverpool FC' },
      { num: 120, name: 'Ryan Gravenberch', team: 'Liverpool FC' },
      { num: 121, name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 122, name: 'Phil Foden', team: 'Manchester City' },
      { num: 123, name: 'Erling Haaland', team: 'Manchester City' },
      { num: 124, name: 'Rayan Cherki', team: 'Manchester City' },
      { num: 125, name: 'Rodri', team: 'Manchester City' },
      { num: 126, name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 127, name: 'Jérémy Doku', team: 'Manchester City' },
      { num: 128, name: 'Abdukodir Khusanov', team: 'Manchester City' },
      { num: 129, name: 'Antoine Semenyo', team: 'Manchester City' },
      { num: 130, name: 'Rúben Dias', team: 'Manchester City' },
      { num: 131, name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 132, name: 'Amir Ibragimov', team: 'Manchester United', isRookie: true },
      { num: 133, name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 134, name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 135, name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 136, name: 'Leny Yoro', team: 'Manchester United' },
      { num: 137, name: 'Casemiro', team: 'Manchester United' },
      { num: 138, name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 139, name: 'Bendito Mantato', team: 'Manchester United', isRookie: true },
      { num: 140, name: 'Jack Fletcher', team: 'Manchester United', isRookie: true },
      { num: 141, name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 142, name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 143, name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 144, name: 'Sven Botman', team: 'Newcastle United' },
      { num: 145, name: 'Malick Thiaw', team: 'Newcastle United' },
      { num: 146, name: 'Jacob Ramsey', team: 'Newcastle United' },
      { num: 147, name: 'Kieran Trippier', team: 'Newcastle United' },
      { num: 148, name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 149, name: 'Harvey Barnes', team: 'Newcastle United' },
      { num: 150, name: 'Joe Willock', team: 'Newcastle United' },
      { num: 151, name: 'Igor Jesus', team: 'Nottingham Forest', isRookie: true },
      { num: 152, name: 'Callum Hudson-Odoi', team: 'Nottingham Forest' },
      { num: 153, name: 'Morgan Gibbs-White', team: 'Nottingham Forest' },
      { num: 154, name: 'Zach Abbott', team: 'Nottingham Forest', isRookie: true },
      { num: 155, name: 'Jair', team: 'Nottingham Forest', isRookie: true },
      { num: 156, name: 'Ibrahim Sangaré', team: 'Nottingham Forest' },
      { num: 157, name: 'Nikola Milenković', team: 'Nottingham Forest' },
      { num: 158, name: 'Murillo', team: 'Nottingham Forest' },
      { num: 159, name: 'Chris Wood', team: 'Nottingham Forest' },
      { num: 160, name: 'Dilane Bakwa', team: 'Nottingham Forest', isRookie: true },
      { num: 161, name: 'Noah Sadiki', team: 'Sunderland', isRookie: true },
      { num: 162, name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 163, name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 164, name: 'Dan Ballard', team: 'Sunderland', isRookie: true },
      { num: 165, name: 'Simon Adingra', team: 'Sunderland' },
      { num: 166, name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 167, name: 'Chemsdine Talbi', team: 'Sunderland' },
      { num: 168, name: 'Nordi Mukiele', team: 'Sunderland' },
      { num: 169, name: 'Robin Roefs', team: 'Sunderland', isRookie: true },
      { num: 170, name: 'Trai Hume', team: 'Sunderland', isRookie: true },
      { num: 171, name: 'Xavi Simons', team: 'Tottenham Hotspur' },
      { num: 172, name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 173, name: 'Kevin Danso', team: 'Tottenham Hotspur' },
      { num: 174, name: 'Richarlison', team: 'Tottenham Hotspur' },
      { num: 175, name: 'Conor Gallagher', team: 'Tottenham Hotspur' },
      { num: 176, name: 'Dominic Solanke', team: 'Tottenham Hotspur' },
      { num: 177, name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 178, name: 'Pape Matar Sarr', team: 'Tottenham Hotspur' },
      { num: 179, name: 'Rodrigo Bentancur', team: 'Tottenham Hotspur' },
      { num: 180, name: 'Cristian Romero', team: 'Tottenham Hotspur' },
      { num: 181, name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 182, name: 'Soungoutou Magassa', team: 'West Ham United' },
      { num: 183, name: 'Crysencio Summerville', team: 'West Ham United' },
      { num: 184, name: 'Konstantinos Mavropanos', team: 'West Ham United' },
      { num: 185, name: 'Freddie Potts', team: 'West Ham United', isRookie: true },
      { num: 186, name: 'Kyle Walker-Peters', team: 'West Ham United' },
      { num: 187, name: 'Mateus Fernandes', team: 'West Ham United' },
      { num: 188, name: 'Mohamadou Kanté', team: 'West Ham United', isRookie: true },
      { num: 189, name: 'Jarrod Bowen', team: 'West Ham United' },
      { num: 190, name: 'Pablo Felipe', team: 'West Ham United', isRookie: true },
      { num: 191, name: 'Tolu Arokodare', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 192, name: 'Jackson Tchatchoua', team: 'Wolverhampton Wanderers' },
      { num: 193, name: 'João Gomes', team: 'Wolverhampton Wanderers' },
      { num: 194, name: 'Fer López', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 195, name: 'Toti Gomes', team: 'Wolverhampton Wanderers' },
      { num: 196, name: 'Hugo Bueno', team: 'Wolverhampton Wanderers' },
      { num: 197, name: 'Ladislav Krejci', team: 'Wolverhampton Wanderers' },
      { num: 198, name: 'David Møller Wolfe', team: 'Wolverhampton Wanderers' },
      { num: 199, name: 'André', team: 'Wolverhampton Wanderers' },
      { num: 200, name: 'Mateus Mané', team: 'Wolverhampton Wanderers', isRookie: true },
    ],
    'Fantasy Football': [
      { num: 'FF-1', name: 'Ben White', team: 'Arsenal' },
      { num: 'FF-2', name: 'Kai Havertz', team: 'Arsenal' },
      { num: 'FF-3', name: 'Emiliano Buendía', team: 'Aston Villa' },
      { num: 'FF-4', name: 'Boubacar Kamara', team: 'Aston Villa' },
      { num: 'FF-5', name: 'David Brooks', team: 'AFC Bournemouth' },
      { num: 'FF-6', name: 'Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 'FF-7', name: 'Fábio Carvalho', team: 'Brentford' },
      { num: 'FF-8', name: 'Aaron Hickey', team: 'Brentford' },
      { num: 'FF-9', name: 'Brajan Gruda', team: 'Brighton & Hove Albion' },
      { num: 'FF-10', name: 'Maxim De Cuyper', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'FF-11', name: 'Quilindschy Hartman', team: 'Burnley FC' },
      { num: 'FF-12', name: 'Jacob Bruun Larsen', team: 'Burnley FC' },
      { num: 'FF-13', name: 'Pedro Neto', team: 'Chelsea' },
      { num: 'FF-14', name: 'Dário Essugo', team: 'Chelsea' },
      { num: 'FF-15', name: 'Daichi Kamada', team: 'Crystal Palace' },
      { num: 'FF-16', name: 'Will Hughes', team: 'Crystal Palace' },
      { num: 'FF-17', name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 'FF-18', name: 'Idrissa Gueye', team: 'Everton' },
      { num: 'FF-19', name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 'FF-20', name: 'Harry Wilson', team: 'Fulham' },
      { num: 'FF-21', name: 'Noah Okafor', team: 'Leeds United' },
      { num: 'FF-22', name: 'Ao Tanaka', team: 'Leeds United' },
      { num: 'FF-23', name: 'Alexis Mac Allister', team: 'Liverpool FC' },
      { num: 'FF-24', name: 'Dominik Szoboszlai', team: 'Liverpool FC' },
      { num: 'FF-25', name: 'Antoine Semenyo', team: 'Manchester City' },
      { num: 'FF-26', name: "Nico O'Reilly", team: 'Manchester City' },
      { num: 'FF-27', name: 'Kobbie Mainoo', team: 'Manchester United' },
      { num: 'FF-28', name: 'Mason Mount', team: 'Manchester United' },
      { num: 'FF-29', name: 'Joelinton', team: 'Newcastle United' },
      { num: 'FF-30', name: 'Fabian Schär', team: 'Newcastle United' },
      { num: 'FF-31', name: 'Callum Hudson-Odoi', team: 'Nottingham Forest' },
      { num: 'FF-32', name: 'Dan Ndoye', team: 'Nottingham Forest' },
      { num: 'FF-33', name: 'Wilson Isidor', team: 'Sunderland', isRookie: true },
      { num: 'FF-34', name: "Luke O'Nien", team: 'Sunderland', isRookie: true },
      { num: 'FF-35', name: 'Cristian Romero', team: 'Tottenham Hotspur' },
      { num: 'FF-36', name: 'Micky van de Ven', team: 'Tottenham Hotspur' },
      { num: 'FF-37', name: 'Crysencio Summerville', team: 'West Ham United' },
      { num: 'FF-38', name: 'Taty Castellanos', team: 'West Ham United' },
      { num: 'FF-39', name: 'Rodrigo Gomes', team: 'Wolverhampton Wanderers' },
      { num: 'FF-40', name: 'Jean-Ricner Bellegarde', team: 'Wolverhampton Wanderers' },
    ],
    'Mystic Afternoons': [
      { num: 'MA-1', name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 'MA-2', name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 'MA-3', name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 'MA-4', name: 'Kevin Schade', team: 'Brentford' },
      { num: 'MA-5', name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'MA-6', name: 'Kyle Walker', team: 'Burnley FC' },
      { num: 'MA-7', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MA-8', name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 'MA-9', name: 'Merlin Röhl', team: 'Everton' },
      { num: 'MA-10', name: 'Enzo Fernández', team: 'Chelsea' },
      { num: 'MA-11', name: 'Dominic Calvert-Lewin', team: 'Leeds United' },
      { num: 'MA-12', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MA-13', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'MA-14', name: 'Casemiro', team: 'Manchester United' },
      { num: 'MA-15', name: 'Anthony Elanga', team: 'Newcastle United' },
      { num: 'MA-16', name: 'Elliot Anderson', team: 'Nottingham Forest' },
      { num: 'MA-17', name: 'Noah Sadiki', team: 'Sunderland', isRookie: true },
      { num: 'MA-18', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'MA-19', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'MA-20', name: 'Tolu Arokodare', team: 'Wolverhampton Wanderers', isRookie: true },
    ],
    "Merlin's Young Magicians": [
      { num: 'YM-1', name: 'Veljko Milosavljević', team: 'AFC Bournemouth', isRookie: true },
      { num: 'YM-2', name: 'Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 'YM-3', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'YM-4', name: 'Bradley Burrowes', team: 'Aston Villa', isRookie: true },
      { num: 'YM-5', name: 'Jamaldeen Jimoh-Aloba', team: 'Aston Villa', isRookie: true },
      { num: 'YM-6', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'YM-7', name: 'Stefanos Tzimas', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'YM-8', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'YM-9', name: 'Jorrel Hato', team: 'Chelsea' },
      { num: 'YM-10', name: 'Tyler Dibling', team: 'Everton' },
      { num: 'YM-11', name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 'YM-12', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'YM-13', name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 'YM-14', name: 'Leny Yoro', team: 'Manchester United' },
      { num: 'YM-15', name: 'Lewis Miley', team: 'Newcastle United' },
      { num: 'YM-16', name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 'YM-17', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'YM-18', name: 'Archie Gray', team: 'Tottenham Hotspur' },
      { num: 'YM-19', name: 'Lucas Bergvall', team: 'Tottenham Hotspur' },
      { num: 'YM-20', name: 'Freddie Potts', team: 'West Ham United', isRookie: true },
    ],
    'Merlin Speaks': [
      { num: 'MS-1', name: 'Riccardo Calafiori', team: 'Arsenal' },
      { num: 'MS-2', name: 'Álex Jiménez', team: 'AFC Bournemouth' },
      { num: 'MS-3', name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 'MS-4', name: 'Carlos Baleba', team: 'Brighton & Hove Albion' },
      { num: 'MS-5', name: 'Loum Tchaouna', team: 'Burnley FC' },
      { num: 'MS-6', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'MS-7', name: 'Eddie Nketiah', team: 'Crystal Palace' },
      { num: 'MS-8', name: 'Jarrad Branthwaite', team: 'Everton' },
      { num: 'MS-9', name: 'Raúl Jiménez', team: 'Fulham' },
      { num: 'MS-10', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'MS-11', name: 'Brenden Aaronson', team: 'Leeds United' },
      { num: 'MS-12', name: 'Rayan Cherki', team: 'Manchester City' },
      { num: 'MS-13', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'MS-14', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'MS-15', name: 'James McAtee', team: 'Nottingham Forest' },
      { num: 'MS-16', name: 'Simon Adingra', team: 'Sunderland' },
      { num: 'MS-17', name: 'Archie Gray', team: 'Tottenham Hotspur' },
      { num: 'MS-18', name: 'Ollie Scarles', team: 'West Ham United' },
      { num: 'MS-19', name: 'Mikkel Damsgaard', team: 'Brentford' },
      { num: 'MS-20', name: 'James Milner', team: 'Brighton & Hove Albion' },
    ],
    'Ta-Da': [
      { num: 'TD-1', name: 'Julio Soler', team: 'AFC Bournemouth', isRookie: true },
      { num: 'TD-2', name: 'Tyler Adams', team: 'AFC Bournemouth' },
      { num: 'TD-3', name: 'Cristhian Mosquera', team: 'Arsenal' },
      { num: 'TD-4', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'TD-5', name: 'Tony Adams', team: 'Arsenal' },
      { num: 'TD-6', name: 'Youri Tielemans', team: 'Aston Villa' },
      { num: 'TD-7', name: 'Lucas Digne', team: 'Aston Villa' },
      { num: 'TD-8', name: 'Gareth Barry', team: 'Aston Villa' },
      { num: 'TD-9', name: 'Vitaly Janelt', team: 'Brentford' },
      { num: 'TD-10', name: 'Mathias Jensen', team: 'Brentford' },
      { num: 'TD-11', name: 'Charalampos Kostoulas', team: 'Brighton & Hove Albion' },
      { num: 'TD-12', name: 'James Milner', team: 'Brighton & Hove Albion' },
      { num: 'TD-13', name: 'Josh Cullen', team: 'Burnley FC' },
      { num: 'TD-14', name: 'Zian Flemming', team: 'Burnley FC', isRookie: true },
      { num: 'TD-15', name: 'Malo Gusto', team: 'Chelsea' },
      { num: 'TD-16', name: 'Alejandro Garnacho', team: 'Chelsea' },
      { num: 'TD-17', name: 'Ashley Cole', team: 'Chelsea' },
      { num: 'TD-18', name: 'Jaydee Canvot', team: 'Crystal Palace', isRookie: true },
      { num: 'TD-19', name: 'João Gomes', team: 'Wolverhampton Wanderers' },
      { num: 'TD-20', name: 'Yannick Bolasie', team: 'Crystal Palace' },
      { num: 'TD-21', name: 'Charly Alcaraz', team: 'Everton' },
      { num: 'TD-22', name: "Jake O'Brien", team: 'Everton' },
      { num: 'TD-23', name: 'Neville Southall', team: 'Everton' },
      { num: 'TD-24', name: 'Tom Cairney', team: 'Fulham' },
      { num: 'TD-25', name: 'Sander Berge', team: 'Fulham' },
      { num: 'TD-26', name: 'Anton Stach', team: 'Leeds United' },
      { num: 'TD-27', name: 'Joe Rodon', team: 'Leeds United' },
      { num: 'TD-28', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'TD-29', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'TD-30', name: 'Fernando Torres', team: 'Liverpool FC' },
      { num: 'TD-31', name: 'Jérémy Doku', team: 'Manchester City' },
      { num: 'TD-32', name: 'Gianluigi Donnarumma', team: 'Manchester City' },
      { num: 'TD-33', name: 'Yaya Touré', team: 'Manchester City' },
      { num: 'TD-34', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'TD-35', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'TD-36', name: 'Robin van Persie', team: 'Manchester United' },
      { num: 'TD-37', name: 'Jacob Murphy', team: 'Newcastle United' },
      { num: 'TD-38', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'TD-39', name: 'Andy Cole', team: 'Newcastle United' },
      { num: 'TD-40', name: 'Nicolò Savona', team: 'Nottingham Forest' },
      { num: 'TD-41', name: 'Ryan Yates', team: 'Nottingham Forest' },
      { num: 'TD-42', name: 'Enzo Le Fée', team: 'Sunderland' },
      { num: 'TD-43', name: 'Robin Roefs', team: 'Sunderland', isRookie: true },
      { num: 'TD-44', name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 'TD-45', name: 'Lucas Bergvall', team: 'Tottenham Hotspur' },
      { num: 'TD-46', name: 'Edgar Davids', team: 'Tottenham Hotspur' },
      { num: 'TD-47', name: 'Callum Wilson', team: 'West Ham United' },
      { num: 'TD-48', name: 'Mateus Fernandes', team: 'West Ham United' },
      { num: 'TD-49', name: 'Matt Doherty', team: 'Wolverhampton Wanderers' },
      { num: 'TD-50', name: 'Hwang Hee-Chan', team: 'Wolverhampton Wanderers' },
    ],
    "Merlin's Mythical Art": [
      { num: 'MM-AN', name: 'Antoine Semenyo', team: 'Manchester City' },
      { num: 'MM-AS', name: 'Alan Shearer', team: 'Newcastle United' },
      { num: 'MM-BM', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'MM-CD', name: 'Clint Dempsey', team: 'Fulham' },
      { num: 'MM-EE', name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 'MM-ES', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MM-FW', name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 'MM-GB', name: 'Gareth Bale', team: 'Tottenham Hotspur' },
      { num: 'MM-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MM-RO', name: 'Rodri', team: 'Manchester City' },
      { num: 'MM-TH', name: 'Thierry Henry', team: 'Arsenal' },
    ],
    'Rainbow Flick': [
      { num: 'RB-1', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'RB-2', name: 'Tyler Dibling', team: 'Everton' },
      { num: 'RB-3', name: 'Chemsdine Talbi', team: 'Sunderland' },
      { num: 'RB-4', name: 'Ryan Gravenberch', team: 'Liverpool FC' },
      { num: 'RB-5', name: 'Gabriel Martinelli', team: 'Arsenal' },
      { num: 'RB-6', name: 'Savinho', team: 'Manchester City' },
      { num: 'RB-7', name: 'Brajan Gruda', team: 'Brighton & Hove Albion' },
      { num: 'RB-8', name: 'Jordan Henderson', team: 'Brentford' },
      { num: 'RB-9', name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 'RB-10', name: 'Kevin', team: 'Fulham' },
      { num: 'RB-11', name: 'Yéremy Pino', team: 'Crystal Palace' },
      { num: 'RB-12', name: 'Wilfried Gnonto', team: 'Leeds United' },
      { num: 'RB-13', name: 'Omari Hutchinson', team: 'Nottingham Forest' },
      { num: 'RB-14', name: 'Wilson Odobert', team: 'Tottenham Hotspur' },
      { num: 'RB-15', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'RB-16', name: 'Fer López', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 'RB-17', name: 'David Ginola', team: 'Aston Villa' },
      { num: 'RB-18', name: 'Justin Kluivert', team: 'AFC Bournemouth' },
      { num: 'RB-19', name: 'Lesley Ugochukwu', team: 'Burnley FC' },
      { num: 'RB-20', name: 'João Pedro', team: 'Chelsea' },
      { num: 'RB-21', name: 'Harry Kane', team: 'Tottenham Hotspur' },
      { num: 'RB-22', name: 'Philippe Coutinho', team: 'Liverpool FC' },
      { num: 'RB-23', name: 'Henrik Larsson', team: 'Manchester United' },
      { num: 'RB-24', name: 'Joe Cole', team: 'West Ham United' },
      { num: 'RB-25', name: 'Hernán Crespo', team: 'Chelsea' },
      { num: 'RB-26', name: 'Sergio Agüero', team: 'Manchester City' },
      { num: 'RB-27', name: 'Leon Osman', team: 'Everton' },
      { num: 'RB-28', name: 'Daniel Sturridge', team: 'Liverpool FC' },
      { num: 'RB-29', name: 'Wayne Rooney', team: 'Manchester United' },
      { num: 'RB-30', name: 'Santi Cazorla', team: 'Arsenal' },
    ],
    'Merlin Premier League 1996 Edition': [
      { num: 'M-1', name: 'Alex Scott', team: 'AFC Bournemouth' },
      { num: 'M-2', name: 'Veljko Milosavljević', team: 'AFC Bournemouth', isRookie: true },
      { num: 'M-3', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'M-4', name: 'Jurriën Timber', team: 'Arsenal' },
      { num: 'M-5', name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 'M-6', name: 'Youri Tielemans', team: 'Aston Villa' },
      { num: 'M-7', name: 'Jamaldeen Jimoh-Aloba', team: 'Aston Villa', isRookie: true },
      { num: 'M-8', name: 'Nathan Collins', team: 'Brentford' },
      { num: 'M-9', name: 'Igor Thiago', team: 'Brentford' },
      { num: 'M-10', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'M-11', name: 'Yankuba Minteh', team: 'Brighton & Hove Albion' },
      { num: 'M-12', name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 'M-13', name: 'Jaidon Anthony', team: 'Burnley FC' },
      { num: 'M-14', name: 'Marcus Edwards', team: 'Burnley FC' },
      { num: 'M-15', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'M-16', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'M-17', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'M-18', name: 'Daniel Muñoz', team: 'Crystal Palace' },
      { num: 'M-19', name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 'M-20', name: 'Jordan Pickford', team: 'Everton' },
      { num: 'M-21', name: 'Jack Grealish', team: 'Everton' },
      { num: 'M-22', name: 'Harry Wilson', team: 'Fulham' },
      { num: 'M-23', name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 'M-24', name: 'Kevin', team: 'Fulham' },
      { num: 'M-25', name: 'Jayden Bogle', team: 'Leeds United' },
      { num: 'M-26', name: 'Anton Stach', team: 'Leeds United' },
      { num: 'M-27', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'M-28', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'M-29', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'M-30', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'M-31', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'M-32', name: 'Rodri', team: 'Manchester City' },
      { num: 'M-33', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'M-34', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'M-35', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'M-36', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'M-37', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'M-38', name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 'M-39', name: 'Igor Jesus', team: 'Nottingham Forest', isRookie: true },
      { num: 'M-40', name: 'Morgan Gibbs-White', team: 'Nottingham Forest' },
      { num: 'M-41', name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 'M-42', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'M-43', name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 'M-44', name: 'Xavi Simons', team: 'Tottenham Hotspur' },
      { num: 'M-45', name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 'M-46', name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 'M-47', name: 'Pablo Felipe', team: 'West Ham United', isRookie: true },
      { num: 'M-48', name: 'Soungoutou Magassa', team: 'West Ham United' },
      { num: 'M-49', name: 'Fer López', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 'M-50', name: 'André', team: 'Wolverhampton Wanderers' },
    ],
    'Magic In His Boots': [
      { num: 'MB-1', name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 'MB-2', name: 'Dennis Bergkamp', team: 'Arsenal' },
      { num: 'MB-3', name: 'Santi Cazorla', team: 'Arsenal' },
      { num: 'MB-4', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'MB-5', name: 'Riccardo Calafiori', team: 'Arsenal' },
      { num: 'MB-6', name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 'MB-7', name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 'MB-8', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'MB-9', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'MB-10', name: 'Eden Hazard', team: 'Chelsea' },
      { num: 'MB-11', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MB-12', name: 'Jack Grealish', team: 'Everton' },
      { num: 'MB-13', name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 'MB-15', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'MB-16', name: 'Juan Mata', team: 'Manchester United' },
      { num: 'MB-17', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MB-18', name: 'Luis Suárez', team: 'Liverpool FC' },
      { num: 'MB-19', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MB-20', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'MB-21', name: 'David Silva', team: 'Manchester City' },
      { num: 'MB-22', name: 'Kevin De Bruyne', team: 'Manchester City' },
      { num: 'MB-23', name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 'MB-24', name: 'Thiago Alcântara', team: 'Liverpool FC' },
      { num: 'MB-25', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'MB-26', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'MB-27', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'MB-28', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'MB-29', name: 'Gareth Bale', team: 'Tottenham Hotspur' },
      { num: 'MB-30', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'MB-31', name: 'Rayan Cherki', team: 'Manchester City' },
      { num: 'MB-32', name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 'MB-33', name: 'Joe Cole', team: 'Chelsea' },
      { num: 'MB-34', name: 'David Ginola', team: 'Tottenham Hotspur' },
      { num: 'MB-35', name: 'Zlatan Ibrahimović', team: 'Manchester United' },
      { num: 'MB-36', name: 'Gianfranco Zola', team: 'Chelsea' },
      { num: 'MB-37', name: 'Riyad Mahrez', team: 'Manchester City' },
      { num: 'MB-38', name: 'Mikkel Damsgaard', team: 'Brentford' },
      { num: 'MB-39', name: 'Dimitar Berbatov', team: 'Fulham' },
      { num: 'MB-40', name: 'Harry Kane', team: 'Tottenham Hotspur' },
    ],
    'The Shiny': [
      { num: 'TS-1', name: 'Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 'TS-2', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'TS-3', name: 'Stiliyan Petrov', team: 'Aston Villa' },
      { num: 'TS-4', name: 'Dango Ouattara', team: 'Brentford' },
      { num: 'TS-5', name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 'TS-6', name: 'Jimmy Floyd Hasselbaink', team: 'Leeds United' },
      { num: 'TS-7', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'TS-8', name: 'Wilfried Zaha', team: 'Crystal Palace' },
      { num: 'TS-9', name: 'Yakubu', team: 'Everton' },
      { num: 'TS-10', name: 'Steed Malbranque', team: 'Fulham' },
      { num: 'TS-11', name: 'Kalvin Phillips', team: 'Leeds United' },
      { num: 'TS-12', name: 'Thiago Alcântara', team: 'Liverpool FC' },
      { num: 'TS-13', name: 'David Silva', team: 'Manchester City' },
      { num: 'TS-14', name: 'Gianfranco Zola', team: 'Chelsea' },
      { num: 'TS-15', name: 'Alan Shearer', team: 'Newcastle United' },
      { num: 'TS-16', name: 'Stuart Pearce', team: 'Nottingham Forest' },
      { num: 'TS-17', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'TS-18', name: 'Heung-Min Son', team: 'Tottenham Hotspur' },
      { num: 'TS-19', name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 'TS-20', name: 'Kevin Doyle', team: 'Wolverhampton Wanderers' },
    ],
    'Renaissance': [
      { num: 'R-1', name: 'Ian Wright', team: 'Arsenal' },
      { num: 'R-2', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'R-3', name: 'Veljko Milosavljević', team: 'AFC Bournemouth', isRookie: true },
      { num: 'R-4', name: 'Igor Thiago', team: 'Brentford' },
      { num: 'R-5', name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 'R-6', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'R-7', name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 'R-8', name: 'Jack Grealish', team: 'Everton' },
      { num: 'R-9', name: 'Louis Saha', team: 'Fulham' },
      { num: 'R-10', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'R-11', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'R-12', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'R-13', name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 'R-14', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'R-15', name: 'Nolberto Solano', team: 'Newcastle United' },
      { num: 'R-16', name: 'Roy Keane', team: 'Nottingham Forest' },
      { num: 'R-17', name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 'R-18', name: 'Luka Modrić', team: 'Tottenham Hotspur' },
      { num: 'R-19', name: 'Joe Cole', team: 'West Ham United' },
      { num: 'R-20', name: 'Michael Carrick', team: 'Manchester United' },
    ],
    "Merlin's Magnum Opus": [
      { num: 'MG-1', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MG-2', name: 'Luis Suárez', team: 'Liverpool FC' },
      { num: 'MG-3', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'MG-4', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'MG-5', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'MG-6', name: 'Didier Drogba', team: 'Chelsea' },
      { num: 'MG-7', name: 'Eden Hazard', team: 'Chelsea' },
      { num: 'MG-8', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MG-9', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MG-10', name: 'Carlos Tevez', team: 'West Ham United' },
      { num: 'MG-11', name: 'Paul Scholes', team: 'Manchester United' },
      { num: 'MG-12', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'MG-13', name: 'Clint Dempsey', team: 'Fulham' },
      { num: 'MG-14', name: 'Thierry Henry', team: 'Arsenal' },
      { num: 'MG-15', name: 'Alan Shearer', team: 'Newcastle United' },
      { num: 'MG-16', name: 'Steven Gerrard', team: 'Liverpool FC' },
      { num: 'MG-17', name: 'Frank Lampard', team: 'Chelsea' },
      { num: 'MG-18', name: 'Kevin De Bruyne', team: 'Manchester City' },
      { num: 'MG-19', name: 'Heung-Min Son', team: 'Tottenham Hotspur' },
      { num: 'MG-20', name: 'Martín Zubimendi', team: 'Arsenal' },
    ],
    'Mask Off': [
      { num: 'MO-1', name: 'Viktor Gyökeres', team: 'Arsenal' },
    ],
    'Autograph Variations': [
      { num: 'MV-AE', name: 'André', team: 'Wolverhampton Wanderers' },
      { num: 'MV-AG', name: 'Alejandro Garnacho', team: 'Chelsea' },
      { num: 'MV-AI', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'MV-AS', name: 'Antoine Semenyo', team: 'Manchester City' },
      { num: 'MV-AX', name: 'Alex Scott', team: 'AFC Bournemouth' },
      { num: 'MV-BG', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'MV-BM', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'MV-BS', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'MV-BU', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'MV-BW', name: 'Jarrod Bowen', team: 'West Ham United' },
      { num: 'MV-BY', name: 'Conor Bradley', team: 'Liverpool FC' },
      { num: 'MV-CG', name: 'Cody Gakpo', team: 'Liverpool FC' },
      { num: 'MV-CM', name: 'Casemiro', team: 'Manchester United' },
      { num: 'MV-CO', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'MV-CP', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'MV-CR', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'MV-CT', name: 'Chemsdine Talbi', team: 'Sunderland' },
      { num: 'MV-CU', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'MV-DJ', name: 'Daniel James', team: 'Leeds United' },
      { num: 'MV-DL', name: 'Matthijs De Ligt', team: 'Manchester United' },
      { num: 'MV-DN', name: 'Kevin Danso', team: 'Tottenham Hotspur' },
      { num: 'MV-DR', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'MV-DS', name: 'Dominic Solanke', team: 'Tottenham Hotspur' },
      { num: 'MV-DW', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'MV-EH', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'MV-EJ', name: 'Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 'MV-EN', name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 'MV-EO', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MV-ESR', name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 'MV-EZE', name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 'MV-FC', name: 'Federico Chiesa', team: 'Liverpool FC' },
      { num: 'MV-FW', name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 'MV-GR', name: 'Conor Gallagher', team: 'Tottenham Hotspur' },
      { num: 'MV-GX', name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 'MV-GY', name: 'Archie Gray', team: 'Tottenham Hotspur' },
      { num: 'MV-IN', name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 'MV-IV', name: 'Amir Ibragimov', team: 'Manchester United', isRookie: true },
      { num: 'MV-JD', name: 'Jérémy Doku', team: 'Manchester City' },
      { num: 'MV-JG', name: 'Jack Grealish', team: 'Everton' },
      { num: 'MV-JH', name: 'Jordan Henderson', team: 'Brentford' },
      { num: 'MV-JY', name: 'Jayden Bogle', team: 'Leeds United' },
      { num: 'MV-KD', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'MV-KDH', name: 'Kiernan Dewsbury-Hall', team: 'Everton' },
      { num: 'MV-KM', name: 'Konstantinos Mavropanos', team: 'West Ham United' },
      { num: 'MV-KS', name: 'Kevin Schade', team: 'Brentford' },
      { num: 'MV-KT', name: 'Kieran Trippier', team: 'Newcastle United' },
      { num: 'MV-KW', name: 'Kyle Walker', team: 'Burnley FC' },
      { num: 'MV-LD', name: 'Lewis Dunk', team: 'Brighton & Hove Albion' },
      { num: 'MV-LN', name: 'Lukas Nmecha', team: 'Leeds United' },
      { num: 'MV-LY', name: 'Leny Yoro', team: 'Manchester United' },
      { num: 'MV-MC', name: 'Matty Cash', team: 'Aston Villa' },
      { num: 'MV-MD', name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 'MV-MK', name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 'MV-MM', name: 'Mikel Merino', team: 'Arsenal' },
      { num: 'MV-MO', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MV-MP', name: 'Jacob Murphy', team: 'Newcastle United' },
      { num: 'MV-MT', name: 'Malick Thiaw', team: 'Newcastle United' },
      { num: 'MV-MØ', name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 'MV-NC', name: 'Nathan Collins', team: 'Brentford' },
      { num: 'MV-OW', name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 'MV-PA', name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 'MV-PD', name: 'Jordan Pickford', team: 'Everton' },
      { num: 'MV-PF', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'MV-RD', name: 'Rúben Dias', team: 'Manchester City' },
      { num: 'MV-RI', name: 'Rodri', team: 'Manchester City' },
      { num: 'MV-RJ', name: 'Reece James', team: 'Chelsea' },
      { num: 'MV-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MV-RS', name: 'Ryan Sessegnon', team: 'Fulham' },
      { num: 'MV-SB', name: 'Sven Botman', team: 'Newcastle United' },
      { num: 'MV-SL', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'MV-ST', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'MV-TD', name: 'Tyler Dibling', team: 'Everton' },
      { num: 'MV-TR', name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 'MV-TW', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'MV-VM', name: 'Vitaliy Mykolenko', team: 'Everton' },
      { num: 'MV-VVD', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'MV-WT', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'MV-YA', name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'MV-YY', name: 'Yehor Yarmolyuk', team: 'Brentford' },
      { num: 'MV-ZA', name: 'Zach Abbott', team: 'Nottingham Forest', isRookie: true },
    ],
    'Mystic Afternoons Autographs': [
      { num: 'MY-AW', name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 'MY-EN', name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 'MY-EO', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MY-ERL', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'MY-KS', name: 'Kevin Schade', team: 'Brentford' },
      { num: 'MY-KW', name: 'Kyle Walker', team: 'Burnley FC' },
      { num: 'MY-MK', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'MY-MØ', name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 'MY-OW', name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 'MY-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MY-YA', name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
    ],
    'Enchanted Pen': [
      { num: 'EP-CP', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'EP-CT', name: 'Carlos Tevez', team: 'West Ham United' },
      { num: 'EP-DL', name: 'David Luiz', team: 'Chelsea' },
      { num: 'EP-DR', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'EP-EA', name: 'Emmanuel Adebayor', team: 'Tottenham Hotspur' },
      { num: 'EP-EH', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'EP-EO', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'EP-EZE', name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 'EP-FC', name: 'Federico Chiesa', team: 'Liverpool FC' },
      { num: 'EP-GZ', name: 'Gianfranco Zola', team: 'Chelsea' },
      { num: 'EP-JG', name: 'Jack Grealish', team: 'Everton' },
      { num: 'EP-KP', name: 'Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 'EP-MM', name: 'Mikel Merino', team: 'Arsenal' },
      { num: 'EP-MT', name: 'Mason Mount', team: 'Manchester United' },
      { num: 'EP-RD', name: 'Rafael van der Vaart', team: 'Tottenham Hotspur' },
      { num: 'EP-RM', name: 'Riyad Mahrez', team: 'Manchester City' },
      { num: 'EP-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'EP-TR', name: 'Tijjani Reijnders', team: 'Manchester City' },
    ],
    'Spellbinding Trios': [
      { num: 'ST-ABY', name: 'Gareth Barry, Gabriel Agbonlahor & Ashley Young', team: 'Aston Villa' },
      { num: 'ST-DSS', name: 'Jérémy Doku, Savinho & Antoine Semenyo', team: 'Manchester City' },
      { num: 'ST-EMØ', name: 'Martin Ødegaard, Eberechi Eze & Mikel Merino', team: 'Arsenal' },
      { num: 'ST-PSH', name: 'Philippe Coutinho, Jordan Henderson & Daniel Sturridge', team: 'Liverpool FC' },
      { num: 'ST-SCS', name: 'Teddy Sheringham, Paul Scholes & Andy Cole', team: 'Manchester United' },
      { num: 'ST-SKS', name: 'Alex Scott, Evanilson & Junior Kroupi', team: 'AFC Bournemouth' },
    ],
    "Merlin's Magical Ink": [
      { num: 'MI-AS', name: 'Alan Shearer', team: 'Newcastle United' },
      { num: 'MI-BM', name: 'David Beckham', team: 'Manchester United' },
      { num: 'MI-CO', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'MI-DB', name: 'Dennis Bergkamp', team: 'Arsenal' },
      { num: 'MI-EH', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'MI-FL', name: 'Frank Lampard', team: 'Chelsea' },
      { num: 'MI-GB', name: 'Gareth Bale', team: 'Tottenham Hotspur' },
      { num: 'MI-GZ', name: 'Gianfranco Zola', team: 'Chelsea' },
      { num: 'MI-HZ', name: 'Eden Hazard', team: 'Chelsea' },
      { num: 'MI-IW', name: 'Ian Wright', team: 'Arsenal' },
      { num: 'MI-JC', name: 'Joe Cole', team: 'West Ham United' },
      { num: 'MI-JF', name: 'Jimmy Floyd Hasselbaink', team: 'Leeds United' },
      { num: 'MI-MD', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'MI-MK', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'MI-MO', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MI-PI', name: 'Paul Ince', team: 'Manchester United' },
      { num: 'MI-PS', name: 'Paul Scholes', team: 'Manchester United' },
      { num: 'MI-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MI-SG', name: 'Steven Gerrard', team: 'Liverpool FC' },
      { num: 'MI-SL', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'MI-SON', name: 'Heung-Min Son', team: 'Tottenham Hotspur' },
      { num: 'MI-TH', name: 'Thierry Henry', team: 'Arsenal' },
      { num: 'MI-TW', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'MI-WR', name: 'Wayne Rooney', team: 'Manchester United' },
      { num: 'MI-ZI', name: 'Zlatan Ibrahimović', team: 'Manchester United' },
    ],
    "Merlin's Match Ball Signatures": [
      { num: 'MB-AR', name: 'Antonee Robinson', team: 'Fulham' },
      { num: 'MB-AS', name: 'Alex Scott', team: 'AFC Bournemouth' },
      { num: 'MB-BA', name: 'Brenden Aaronson', team: 'Leeds United' },
      { num: 'MB-BB', name: 'Bradley Burrowes', team: 'Aston Villa', isRookie: true },
      { num: 'MB-BF', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'MB-BG', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'MB-BM', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'MB-BS', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'MB-CR', name: 'Cristian Romero', team: 'Tottenham Hotspur' },
      { num: 'MB-DM', name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 'MB-DW', name: 'Danny Welbeck', team: 'Brighton & Hove Albion' },
      { num: 'MB-EH', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'MB-EM', name: 'Emiliano Martínez', team: 'Aston Villa' },
      { num: 'MB-EZE', name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 'MB-GR', name: 'Georginio Rutter', team: 'Brighton & Hove Albion' },
      { num: 'MB-JZ', name: 'Joshua Zirkzee', team: 'Manchester United' },
      { num: 'MB-KS', name: 'Kevin Schade', team: 'Brentford' },
      { num: 'MB-MC', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'MB-MS', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MB-MT', name: 'Mathys Tel', team: 'Tottenham Hotspur' },
      { num: 'MB-NM', name: 'Nikola Milenković', team: 'Nottingham Forest' },
      { num: 'MB-OW', name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 'MB-PF', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'MB-PK', name: 'Jordan Pickford', team: 'Everton' },
      { num: 'MB-RG', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'MB-RIO', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'MB-SE', name: 'Antoine Semenyo', team: 'Manchester City' },
      { num: 'MB-SL', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'MB-SV', name: 'Savinho', team: 'Manchester City' },
      { num: 'MB-TI', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'MB-TR', name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 'MB-VVD', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'MB-WS', name: 'William Saliba', team: 'Arsenal' },
    ],
  },
};