import type { Checklist } from './index';

export const toppsFinestPremierLeague2026: Checklist = {
  setSlug: 'topps-finest-premier-league-2026',
  setName: 'Topps Finest Premier League 2026',
  setBadge: '⚡ Out Now',
  setSubtitle: 'Topps · 2025-26 · Full Checklist',
  ebaySearchSuffix: 'Topps Finest Premier League',
  filterDimension: {
    field: 'team',
    label: 'Team',
    placeholder: 'All Teams',
  },
  sectionColors: {
    'Base Common': '#3aaa35',
    'Base Uncommon': '#3aaa35',
    'Base Rare': '#3aaa35',
    'Expected Brilliance': '#3aaa35',
    'Swerve': '#3aaa35',
    'Arrivals': '#3aaa35',
    'Clean': '#3aaa35',
    'Gusto': '#f59e0b',
    'Nightmare Fuel': '#f59e0b',
    'Main Attraction': '#f59e0b',
    'Polka': '#3aaa35',
    'Headliners': '#3aaa35',
    'Aura': '#3aaa35',
    'Finest Idols': '#f59e0b',
    'Finest Autographs': '#3aaa35',
    'Finest Moments Autographs': '#3aaa35',
    'Finest Seasons 1995-96': '#3aaa35',
    'Finest Partnerships': '#3aaa35',
    'Arrivals Autograph Edition': '#3aaa35',
    'Main Attraction Autograph Edition': '#f59e0b',
    'Gustographs': '#3aaa35',
    'Finest Fans': '#3aaa35',
  },
  sections: {
    'Base Common': [
      { num: 1, name: 'Antoine Semenyo', team: 'AFC Bournemouth' },
      { num: 2, name: 'Julio Soler', team: 'AFC Bournemouth', isRookie: true },
      { num: 3, name: 'Eli Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 4, name: 'Amine Adli', team: 'AFC Bournemouth' },
      { num: 5, name: 'Leandro Trossard', team: 'Arsenal' },
      { num: 6, name: 'Jurriën Timber', team: 'Arsenal' },
      { num: 7, name: 'Riccardo Calafiori', team: 'Arsenal' },
      { num: 8, name: 'Noni Madueke', team: 'Arsenal' },
      { num: 9, name: 'Ben Broggio', team: 'Aston Villa', isRookie: true },
      { num: 10, name: 'Rory Wilson', team: 'Aston Villa', isRookie: true },
      { num: 11, name: 'Jamaldeen Jimoh-Aloba', team: 'Aston Villa', isRookie: true },
      { num: 12, name: 'Mikkel Damsgaard', team: 'Brentford' },
      { num: 13, name: 'Kevin Schade', team: 'Brentford' },
      { num: 14, name: 'Michael Kayode', team: 'Brentford' },
      { num: 15, name: 'Dango Ouattara', team: 'Brentford' },
      { num: 16, name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 17, name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 18, name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 19, name: 'Harry Howell', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 20, name: 'Jaidon Anthony', team: 'Burnley FC' },
      { num: 21, name: 'Lyle Foster', team: 'Burnley FC' },
      { num: 22, name: 'Lesley Ugochukwu', team: 'Burnley FC' },
      { num: 23, name: 'Jaydon Banel', team: 'Burnley FC', isRookie: true },
      { num: 24, name: 'Bashir Humphreys', team: 'Burnley FC', isRookie: true },
      { num: 25, name: 'Zian Flemming', team: 'Burnley FC', isRookie: true },
      { num: 26, name: 'Kyle Walker', team: 'Burnley FC' },
      { num: 27, name: 'Josh Laurent', team: 'Burnley FC', isRookie: true },
      { num: 28, name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 29, name: 'Cole Palmer', team: 'Chelsea' },
      { num: 30, name: 'Josh Acheampong', team: 'Chelsea' },
      { num: 31, name: 'Shumaira Mheuka', team: 'Chelsea', isRookie: true },
      { num: 32, name: 'Harrison Murray-Campbell', team: 'Chelsea', isRookie: true },
      { num: 33, name: 'Romain Esse', team: 'Crystal Palace', isRookie: true },
      { num: 34, name: 'Zach Marsh', team: 'Crystal Palace', isRookie: true },
      { num: 35, name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 36, name: 'Justin Devenny', team: 'Crystal Palace', isRookie: true },
      { num: 37, name: 'Yéremy Pino', team: 'Crystal Palace' },
      { num: 38, name: 'Jack Grealish', team: 'Everton' },
      { num: 39, name: 'Kiernan Dewsbury-Hall', team: 'Everton' },
      { num: 40, name: 'Tyler Dibling', team: 'Everton' },
      { num: 41, name: 'Roman Dixon', team: 'Everton', isRookie: true },
      { num: 42, name: 'Charly Alcaraz', team: 'Everton' },
      { num: 43, name: 'Jonah Kusi-Asare', team: 'Fulham', isRookie: true },
      { num: 44, name: 'Samuel Chukwueze', team: 'Fulham' },
      { num: 45, name: 'Kevin', team: 'Fulham' },
      { num: 46, name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 47, name: 'Gabriel Gudmundsson', team: 'Leeds United' },
      { num: 48, name: 'Noah Okafor', team: 'Leeds United' },
      { num: 49, name: 'Anton Stach', team: 'Leeds United' },
      { num: 50, name: 'Dominic Calvert-Lewin', team: 'Leeds United' },
      { num: 51, name: 'Harry Gray', team: 'Leeds United', isRookie: true },
      { num: 52, name: 'Alfie Cresswell', team: 'Leeds United', isRookie: true },
      { num: 53, name: 'Sean Longstaff', team: 'Leeds United' },
      { num: 54, name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 55, name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 56, name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 57, name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 58, name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 59, name: 'Trent Koné-Doherty', team: 'Liverpool FC', isRookie: true },
      { num: 60, name: 'Giovanni Leoni', team: 'Liverpool FC', isRookie: true },
      { num: 61, name: 'Erling Haaland', team: 'Manchester City' },
      { num: 62, name: 'Rayan Cherki', team: 'Manchester City' },
      { num: 63, name: 'Rodri', team: 'Manchester City' },
      { num: 64, name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 65, name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 66, name: 'Gianluigi Donnarumma', team: 'Manchester City' },
      { num: 67, name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 68, name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 69, name: 'Amir Ibragimov', team: 'Manchester United', isRookie: true },
      { num: 70, name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 71, name: 'Bendito Mantato', team: 'Manchester United', isRookie: true },
      { num: 72, name: 'Joelinton', team: 'Newcastle United' },
      { num: 73, name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 74, name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 75, name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 76, name: 'Seung-Soo Park', team: 'Newcastle United', isRookie: true },
      { num: 77, name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 78, name: 'Morgan Gibbs-White', team: 'Nottingham Forest' },
      { num: 79, name: 'James McAtee', team: 'Nottingham Forest' },
      { num: 80, name: 'Igor Jesus', team: 'Nottingham Forest', isRookie: true },
      { num: 81, name: 'Zach Abbott', team: 'Nottingham Forest', isRookie: true },
      { num: 82, name: 'Jair', team: 'Nottingham Forest', isRookie: true },
      { num: 83, name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 84, name: 'Noah Sadiki', team: 'Sunderland', isRookie: true },
      { num: 85, name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 86, name: 'Wilson Isidor', team: 'Sunderland', isRookie: true },
      { num: 87, name: 'Simon Adingra', team: 'Sunderland' },
      { num: 88, name: 'Lucas Bergvall', team: 'Tottenham Hotspur' },
      { num: 89, name: 'Djed Spence', team: 'Tottenham Hotspur' },
      { num: 90, name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 91, name: 'Xavi Simons', team: 'Tottenham Hotspur' },
      { num: 92, name: 'Kōta Takai', team: 'Tottenham Hotspur', isRookie: true },
      { num: 93, name: 'Crysencio Summerville', team: 'West Ham United' },
      { num: 94, name: 'Lucas Paquetá', team: 'West Ham United' },
      { num: 95, name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 96, name: 'Freddie Potts', team: 'West Ham United', isRookie: true },
      { num: 97, name: 'Callum Marshall', team: 'West Ham United' },
      { num: 98, name: 'Fer López', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 99, name: 'Enso González', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 100, name: 'Wesley Okoduwa', team: 'Wolverhampton Wanderers', isRookie: true },
    ],
    'Base Uncommon': [
      { num: 101, name: 'Antoine Semenyo', team: 'AFC Bournemouth' },
      { num: 102, name: 'Justin Kluivert', team: 'AFC Bournemouth' },
      { num: 103, name: 'Tyler Adams', team: 'AFC Bournemouth' },
      { num: 104, name: 'Eli Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 105, name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 106, name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 107, name: 'Gabriel Magalhães', team: 'Arsenal' },
      { num: 108, name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 109, name: 'Viktor Gyökeres', team: 'Arsenal' },
      { num: 110, name: 'Jaydee Canvot', team: 'Crystal Palace', isRookie: true },
      { num: 111, name: 'Cristhian Mosquera', team: 'Arsenal' },
      { num: 112, name: 'William Saliba', team: 'Arsenal' },
      { num: 113, name: 'Piero Hincapié', team: 'Arsenal' },
      { num: 114, name: 'Igor Thiago', team: 'Brentford' },
      { num: 115, name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 116, name: 'Ben Broggio', team: 'Aston Villa', isRookie: true },
      { num: 117, name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 118, name: 'Youri Tielemans', team: 'Aston Villa' },
      { num: 119, name: 'John McGinn', team: 'Aston Villa' },
      { num: 120, name: 'Jamaldeen Jimoh-Aloba', team: 'Aston Villa', isRookie: true },
      { num: 121, name: 'Jair', team: 'Nottingham Forest', isRookie: true },
      { num: 122, name: 'Mikkel Damsgaard', team: 'Brentford' },
      { num: 123, name: 'Dango Ouattara', team: 'Brentford' },
      { num: 124, name: 'Gustavo Nunes', team: 'Brentford', isRookie: true },
      { num: 125, name: 'Nathan Collins', team: 'Brentford' },
      { num: 126, name: 'Romelle Donovan', team: 'Brentford', isRookie: true },
      { num: 127, name: 'Jordan Henderson', team: 'Brentford' },
      { num: 128, name: 'Antoni Milambo', team: 'Brentford' },
      { num: 129, name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 130, name: 'Stefanos Tzimas', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 131, name: 'Brajan Gruda', team: 'Brighton & Hove Albion' },
      { num: 132, name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 133, name: 'Yankuba Minteh', team: 'Brighton & Hove Albion' },
      { num: 134, name: 'Josh Laurent', team: 'Burnley FC', isRookie: true },
      { num: 135, name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 136, name: 'Cole Palmer', team: 'Chelsea' },
      { num: 137, name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 138, name: 'Enzo Fernández', team: 'Chelsea' },
      { num: 139, name: 'Alejandro Garnacho', team: 'Chelsea' },
      { num: 140, name: 'Jean-Philippe Mateta', team: 'Crystal Palace' },
      { num: 141, name: 'Christantus Uche', team: 'Crystal Palace' },
      { num: 142, name: 'Yéremy Pino', team: 'Crystal Palace' },
      { num: 143, name: 'Jack Grealish', team: 'Everton' },
      { num: 144, name: 'Charly Alcaraz', team: 'Everton' },
      { num: 145, name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 146, name: 'Dwight McNeil', team: 'Everton' },
      { num: 147, name: 'Jarrad Branthwaite', team: 'Everton' },
      { num: 148, name: 'Thierno Barry', team: 'Everton' },
      { num: 149, name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 150, name: 'Kevin', team: 'Fulham' },
      { num: 151, name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 152, name: 'Raúl Jiménez', team: 'Fulham' },
      { num: 153, name: 'Brenden Aaronson', team: 'Leeds United' },
      { num: 154, name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 155, name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 156, name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 157, name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 158, name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 159, name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 160, name: 'Erling Haaland', team: 'Manchester City' },
      { num: 161, name: 'Rayan Cherki', team: 'Manchester City' },
      { num: 162, name: 'Rodri', team: 'Manchester City' },
      { num: 163, name: 'Omar Marmoush', team: 'Manchester City' },
      { num: 164, name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 165, name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 166, name: 'Reigan Heskey', team: 'Manchester City', isRookie: true },
      { num: 167, name: 'Phil Foden', team: 'Manchester City' },
      { num: 168, name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 169, name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 170, name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 171, name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 172, name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 173, name: 'Fabian Schär', team: 'Newcastle United' },
      { num: 174, name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 175, name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 176, name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 177, name: 'Morgan Gibbs-White', team: 'Nottingham Forest' },
      { num: 178, name: 'James McAtee', team: 'Nottingham Forest' },
      { num: 179, name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 180, name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 181, name: 'Noah Sadiki', team: 'Sunderland', isRookie: true },
      { num: 182, name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 183, name: 'Enzo Le Fée', team: 'Sunderland' },
      { num: 184, name: 'Simon Adingra', team: 'Sunderland' },
      { num: 185, name: 'Wilson Odobert', team: 'Tottenham Hotspur' },
      { num: 186, name: 'Pape Matar Sarr', team: 'Tottenham Hotspur' },
      { num: 187, name: 'Pedro Porro', team: 'Tottenham Hotspur' },
      { num: 188, name: 'Xavi Simons', team: 'Tottenham Hotspur' },
      { num: 189, name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 190, name: 'Crysencio Summerville', team: 'West Ham United' },
      { num: 191, name: 'Lucas Paquetá', team: 'West Ham United' },
      { num: 192, name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 193, name: 'Freddie Potts', team: 'West Ham United', isRookie: true },
      { num: 194, name: 'Luis Guilherme', team: 'West Ham United', isRookie: true },
      { num: 195, name: 'Ollie Scarles', team: 'West Ham United' },
      { num: 196, name: 'Jørgen Strand Larsen', team: 'Wolverhampton Wanderers' },
      { num: 197, name: 'André', team: 'Wolverhampton Wanderers' },
      { num: 198, name: 'João Gomes', team: 'Wolverhampton Wanderers' },
      { num: 199, name: 'Jhon Arias', team: 'Wolverhampton Wanderers' },
      { num: 200, name: 'Tolu Arokodare', team: 'Wolverhampton Wanderers', isRookie: true },
    ],
    'Base Rare': [
      { num: 201, name: 'Antoine Semenyo', team: 'AFC Bournemouth' },
      { num: 202, name: 'Amine Adli', team: 'AFC Bournemouth' },
      { num: 203, name: 'Tyler Adams', team: 'AFC Bournemouth' },
      { num: 204, name: 'Eli Junior Kroupi', team: 'AFC Bournemouth' },
      { num: 205, name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 206, name: 'Veljko Milosavljević', team: 'AFC Bournemouth', isRookie: true },
      { num: 207, name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 208, name: 'Viktor Gyökeres', team: 'Arsenal' },
      { num: 209, name: 'Maxim De Cuyper', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 210, name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 211, name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 212, name: 'Declan Rice', team: 'Arsenal' },
      { num: 213, name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 214, name: 'Myles Lewis-Skelly', team: 'Arsenal' },
      { num: 215, name: 'Jamaldeen Jimoh-Aloba', team: 'Aston Villa', isRookie: true },
      { num: 216, name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 217, name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 218, name: 'Youri Tielemans', team: 'Aston Villa' },
      { num: 219, name: 'Kevin Schade', team: 'Brentford' },
      { num: 220, name: 'Dango Ouattara', team: 'Brentford' },
      { num: 221, name: 'Romelle Donovan', team: 'Brentford', isRookie: true },
      { num: 222, name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 223, name: 'Harry Howell', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 224, name: 'Brajan Gruda', team: 'Brighton & Hove Albion' },
      { num: 225, name: 'Stefanos Tzimas', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 226, name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 227, name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 228, name: 'Quilindschy Hartman', team: 'Burnley FC' },
      { num: 229, name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 230, name: 'Cole Palmer', team: 'Chelsea' },
      { num: 231, name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 232, name: 'Enzo Fernández', team: 'Chelsea' },
      { num: 233, name: 'Jorrel Hato', team: 'Chelsea' },
      { num: 234, name: 'Liam Delap', team: 'Chelsea' },
      { num: 235, name: 'João Pedro', team: 'Chelsea' },
      { num: 236, name: 'Adam Wharton', team: 'Crystal Palace' },
      { num: 237, name: 'Jean-Philippe Mateta', team: 'Crystal Palace' },
      { num: 238, name: 'Chris Richards', team: 'Crystal Palace' },
      { num: 239, name: 'Daichi Kamada', team: 'Crystal Palace' },
      { num: 240, name: 'Daniel Muñoz', team: 'Crystal Palace' },
      { num: 241, name: 'Yéremy Pino', team: 'Crystal Palace' },
      { num: 242, name: 'Christantus Uche', team: 'Crystal Palace' },
      { num: 243, name: 'Jack Grealish', team: 'Everton' },
      { num: 244, name: 'Tyler Dibling', team: 'Everton' },
      { num: 245, name: 'Charly Alcaraz', team: 'Everton' },
      { num: 246, name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 247, name: 'Thierno Barry', team: 'Everton' },
      { num: 248, name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 249, name: 'Raúl Jiménez', team: 'Fulham' },
      { num: 250, name: 'Alex Iwobi', team: 'Fulham' },
      { num: 251, name: 'Rodrigo Muniz', team: 'Fulham' },
      { num: 252, name: 'Adama Traoré', team: 'Fulham' },
      { num: 253, name: 'Reggie Walsh', team: 'Chelsea', isRookie: true },
      { num: 254, name: 'Harry Gray', team: 'Leeds United', isRookie: true },
      { num: 255, name: 'Ao Tanaka', team: 'Leeds United' },
      { num: 256, name: 'Jayden Bogle', team: 'Leeds United' },
      { num: 257, name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 258, name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 259, name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 260, name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 261, name: 'Hugo Ekitiké', team: 'Liverpool FC' },
      { num: 262, name: 'Alexis Mac Allister', team: 'Liverpool FC' },
      { num: 263, name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 264, name: 'Erling Haaland', team: 'Manchester City' },
      { num: 265, name: 'Rodri', team: 'Manchester City' },
      { num: 266, name: 'Omar Marmoush', team: 'Manchester City' },
      { num: 267, name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 268, name: 'Phil Foden', team: 'Manchester City' },
      { num: 269, name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 270, name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 271, name: 'Amir Ibragimov', team: 'Manchester United', isRookie: true },
      { num: 272, name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 273, name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 274, name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 275, name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 276, name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 277, name: 'Joelinton', team: 'Newcastle United' },
      { num: 278, name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 279, name: 'Seung-Soo Park', team: 'Newcastle United', isRookie: true },
      { num: 280, name: 'Anthony Elanga', team: 'Newcastle United' },
      { num: 281, name: 'James McAtee', team: 'Nottingham Forest' },
      { num: 282, name: 'Igor Jesus', team: 'Nottingham Forest', isRookie: true },
      { num: 283, name: 'Callum Hudson-Odoi', team: 'Nottingham Forest' },
      { num: 284, name: 'Morgan Gibbs-White', team: 'Nottingham Forest' },
      { num: 285, name: 'Murillo', team: 'Nottingham Forest' },
      { num: 286, name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 287, name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 288, name: 'Xavi Simons', team: 'Tottenham Hotspur' },
      { num: 289, name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 290, name: 'Dominic Solanke', team: 'Tottenham Hotspur' },
      { num: 291, name: 'Archie Gray', team: 'Tottenham Hotspur' },
      { num: 292, name: 'Lucas Bergvall', team: 'Tottenham Hotspur' },
      { num: 293, name: 'Micky van de Ven', team: 'Tottenham Hotspur' },
      { num: 294, name: 'Lucas Paquetá', team: 'West Ham United' },
      { num: 295, name: 'Jarrod Bowen', team: 'West Ham United' },
      { num: 296, name: 'João Gomes', team: 'Wolverhampton Wanderers' },
      { num: 297, name: 'André', team: 'Wolverhampton Wanderers' },
      { num: 298, name: 'Jørgen Strand Larsen', team: 'Wolverhampton Wanderers' },
      { num: 299, name: 'Jhon Arias', team: 'Wolverhampton Wanderers' },
      { num: 300, name: 'Enso González', team: 'Wolverhampton Wanderers', isRookie: true },
    ],
    'Expected Brilliance': [
      { num: 'XB-1', name: 'Evanilson', team: 'AFC Bournemouth' },
      { num: 'XB-2', name: 'Antoine Semenyo', team: 'AFC Bournemouth' },
      { num: 'XB-3', name: 'Eberechi Eze', team: 'Arsenal' },
      { num: 'XB-4', name: 'Viktor Gyökeres', team: 'Arsenal' },
      { num: 'XB-5', name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 'XB-6', name: 'Harvey Elliott', team: 'Aston Villa' },
      { num: 'XB-7', name: 'Dango Ouattara', team: 'Brentford' },
      { num: 'XB-8', name: 'Mikkel Damsgaard', team: 'Brentford' },
      { num: 'XB-9', name: 'Charalampos Kostoulas', team: 'Brighton & Hove Albion' },
      { num: 'XB-10', name: 'Stefanos Tzimas', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'XB-11', name: 'Armando Broja', team: 'Burnley FC' },
      { num: 'XB-12', name: 'Jaidon Anthony', team: 'Burnley FC' },
      { num: 'XB-13', name: 'Facundo Buonanotte', team: 'Chelsea' },
      { num: 'XB-14', name: 'João Pedro', team: 'Chelsea' },
      { num: 'XB-15', name: 'Jean-Philippe Mateta', team: 'Crystal Palace' },
      { num: 'XB-16', name: 'Yéremy Pino', team: 'Crystal Palace' },
      { num: 'XB-17', name: 'Charly Alcaraz', team: 'Everton' },
      { num: 'XB-18', name: 'Thierno Barry', team: 'Everton' },
      { num: 'XB-19', name: 'Jonah Kusi-Asare', team: 'Fulham', isRookie: true },
      { num: 'XB-20', name: 'Kevin', team: 'Fulham' },
      { num: 'XB-21', name: 'Harry Gray', team: 'Leeds United', isRookie: true },
      { num: 'XB-22', name: 'Wilfried Gnonto', team: 'Leeds United' },
      { num: 'XB-23', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'XB-24', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'XB-25', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'XB-26', name: 'Omar Marmoush', team: 'Manchester City' },
      { num: 'XB-27', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'XB-28', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'XB-29', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'XB-30', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'XB-31', name: 'Chris Wood', team: 'Nottingham Forest' },
      { num: 'XB-32', name: 'Arnaud Kalimuendo', team: 'Nottingham Forest' },
      { num: 'XB-33', name: 'Eliezer Mayenda', team: 'Sunderland', isRookie: true },
      { num: 'XB-34', name: 'Habib Diarra', team: 'Sunderland' },
      { num: 'XB-35', name: 'Xavi Simons', team: 'Tottenham Hotspur' },
      { num: 'XB-36', name: 'Randal Kolo Muani', team: 'Tottenham Hotspur' },
      { num: 'XB-37', name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 'XB-38', name: 'Mateus Fernandes', team: 'West Ham United' },
      { num: 'XB-39', name: 'Tolu Arokodare', team: 'Wolverhampton Wanderers', isRookie: true },
      { num: 'XB-40', name: 'Fer López', team: 'Wolverhampton Wanderers', isRookie: true },
    ],
    'Swerve': [
      { num: 'SV-1', name: 'Justin Kluivert', team: 'AFC Bournemouth' },
      { num: 'SV-2', name: 'Amine Adli', team: 'AFC Bournemouth' },
      { num: 'SV-3', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'SV-4', name: 'Ethan Nwaneri', team: 'Arsenal' },
      { num: 'SV-5', name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 'SV-6', name: 'Youri Tielemans', team: 'Aston Villa' },
      { num: 'SV-7', name: 'Antoni Milambo', team: 'Brentford' },
      { num: 'SV-8', name: 'Romelle Donovan', team: 'Brentford', isRookie: true },
      { num: 'SV-9', name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'SV-10', name: 'Brajan Gruda', team: 'Brighton & Hove Albion' },
      { num: 'SV-11', name: 'Lesley Ugochukwu', team: 'Burnley FC' },
      { num: 'SV-12', name: 'Quilindschy Hartman', team: 'Burnley FC' },
      { num: 'SV-13', name: 'Dário Essugo', team: 'Chelsea' },
      { num: 'SV-14', name: 'Alejandro Garnacho', team: 'Chelsea' },
      { num: 'SV-15', name: 'Ismaïla Sarr', team: 'Crystal Palace' },
      { num: 'SV-16', name: 'Romain Esse', team: 'Crystal Palace', isRookie: true },
      { num: 'SV-17', name: 'Kiernan Dewsbury-Hall', team: 'Everton' },
      { num: 'SV-18', name: 'Tyler Dibling', team: 'Everton' },
      { num: 'SV-19', name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 'SV-20', name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 'SV-21', name: 'Brenden Aaronson', team: 'Leeds United' },
      { num: 'SV-22', name: 'Ao Tanaka', team: 'Leeds United' },
      { num: 'SV-23', name: 'Alexis Mac Allister', team: 'Liverpool FC' },
      { num: 'SV-24', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'SV-25', name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 'SV-26', name: 'Jérémy Doku', team: 'Manchester City' },
      { num: 'SV-27', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'SV-28', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'SV-29', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'SV-30', name: 'Tino Livramento', team: 'Newcastle United' },
      { num: 'SV-31', name: 'Arnaud Kalimuendo', team: 'Nottingham Forest' },
      { num: 'SV-32', name: 'Ryan Yates', team: 'Nottingham Forest' },
      { num: 'SV-33', name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 'SV-34', name: 'Enzo Le Fée', team: 'Sunderland' },
      { num: 'SV-35', name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 'SV-36', name: 'Lucas Bergvall', team: 'Tottenham Hotspur' },
      { num: 'SV-37', name: 'Lucas Paquetá', team: 'West Ham United' },
      { num: 'SV-38', name: 'Luis Guilherme', team: 'West Ham United', isRookie: true },
      { num: 'SV-39', name: 'Jhon Arias', team: 'Wolverhampton Wanderers' },
      { num: 'SV-40', name: 'João Gomes', team: 'Wolverhampton Wanderers' },
    ],
    'Arrivals': [
      { num: 'AV-1', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'AV-2', name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 'AV-3', name: 'Reggie Walsh', team: 'Chelsea', isRookie: true },
      { num: 'AV-4', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'AV-5', name: 'Harry Gray', team: 'Leeds United', isRookie: true },
      { num: 'AV-6', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'AV-7', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'AV-8', name: 'Jaydee Canvot', team: 'Crystal Palace', isRookie: true },
      { num: 'AV-9', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'AV-10', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
    ],
    'Clean': [
      { num: 'CN-1', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'CN-2', name: 'Riccardo Calafiori', team: 'Arsenal' },
      { num: 'CN-3', name: 'David Raya', team: 'Arsenal' },
      { num: 'CN-4', name: 'Dan Burn', team: 'Newcastle United' },
      { num: 'CN-5', name: 'Micky van de Ven', team: 'Tottenham Hotspur' },
      { num: 'CN-6', name: 'Jorrel Hato', team: 'Chelsea' },
      { num: 'CN-7', name: 'Nathan Collins', team: 'Brentford' },
      { num: 'CN-8', name: 'Murillo', team: 'Nottingham Forest' },
      { num: 'CN-9', name: 'Gianluigi Donnarumma', team: 'Manchester City' },
      { num: 'CN-10', name: 'Lewis Dunk', team: 'Brighton & Hove Albion' },
    ],
    'Gusto': [
      { num: 'GO-1', name: 'Kai Havertz', team: 'Arsenal' },
      { num: 'GO-2', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'GO-3', name: 'Jarrod Bowen', team: 'West Ham United' },
      { num: 'GO-4', name: 'Diego León', team: 'Manchester United', isRookie: true },
      { num: 'GO-5', name: 'Heung-Min Son', team: 'Tottenham Hotspur' },
      { num: 'GO-6', name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 'GO-7', name: 'Yaya Touré', team: 'Manchester City' },
      { num: 'GO-8', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'GO-9', name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 'GO-10', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'GO-11', name: 'Alexis Mac Allister', team: 'Liverpool FC' },
      { num: 'GO-12', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'GO-13', name: 'Dominik Szoboszlai', team: 'Liverpool FC' },
      { num: 'GO-14', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'GO-15', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'GO-16', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'GO-17', name: 'Enzo Fernández', team: 'Chelsea' },
      { num: 'GO-18', name: 'João Pedro', team: 'Chelsea' },
      { num: 'GO-19', name: 'Malo Gusto', team: 'Chelsea' },
      { num: 'GO-20', name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
    ],
    'Nightmare Fuel': [
      { num: 'NF-1', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'NF-2', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'NF-3', name: 'Viktor Gyökeres', team: 'Arsenal' },
      { num: 'NF-4', name: 'Carlos Tevez', team: 'Manchester City' },
      { num: 'NF-5', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'NF-6', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'NF-7', name: 'Wayne Rooney', team: 'Manchester United' },
      { num: 'NF-8', name: 'Harry Kane', team: 'Tottenham Hotspur' },
      { num: 'NF-9', name: 'Fernando Torres', team: 'Liverpool FC' },
      { num: 'NF-10', name: 'Dennis Bergkamp', team: 'Arsenal' },
      { num: 'NF-11', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'NF-12', name: 'Didier Drogba', team: 'Chelsea' },
      { num: 'NF-13', name: 'Robbie Fowler', team: 'Liverpool FC' },
      { num: 'NF-14', name: 'Eric Cantona', team: 'Manchester United' },
      { num: 'NF-15', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'NF-16', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'NF-17', name: 'Sergio Agüero', team: 'Manchester City' },
      { num: 'NF-18', name: 'Thierry Henry', team: 'Arsenal' },
      { num: 'NF-19', name: 'Ian Wright', team: 'Arsenal' },
      { num: 'NF-20', name: 'Alan Shearer', team: 'Newcastle United' },
    ],
    'Main Attraction': [
      { num: 'MA-1', name: 'Antoine Semenyo', team: 'AFC Bournemouth' },
      { num: 'MA-2', name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 'MA-3', name: 'Rodri', team: 'Manchester City' },
      { num: 'MA-4', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'MA-5', name: 'Gareth Bale', team: 'Tottenham Hotspur' },
      { num: 'MA-6', name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 'MA-7', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MA-8', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'MA-9', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'MA-10', name: 'Kaoru Mitoma', team: 'Brighton & Hove Albion' },
      { num: 'MA-11', name: 'David Silva', team: 'Manchester City' },
      { num: 'MA-12', name: 'Ethan Nwaneri', team: 'Arsenal' },
      { num: 'MA-13', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'MA-14', name: 'Andy Cole', team: 'Manchester United' },
      { num: 'MA-15', name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 'MA-16', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MA-17', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'MA-18', name: 'Carlos Tevez', team: 'Manchester City' },
      { num: 'MA-19', name: 'Kevin', team: 'Fulham' },
      { num: 'MA-20', name: 'Luka Modrić', team: 'Tottenham Hotspur' },
    ],
    'Polka': [
      { num: 'PK-1', name: 'David Beckham', team: 'Manchester United' },
      { num: 'PK-2', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'PK-3', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'PK-4', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'PK-5', name: 'Kevin De Bruyne', team: 'Manchester City' },
      { num: 'PK-6', name: 'Gareth Bale', team: 'Tottenham Hotspur' },
      { num: 'PK-7', name: 'Harry Kane', team: 'Tottenham Hotspur' },
      { num: 'PK-8', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'PK-9', name: 'Eden Hazard', team: 'Chelsea' },
      { num: 'PK-10', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'PK-11', name: 'Heung-Min Son', team: 'Tottenham Hotspur' },
      { num: 'PK-12', name: 'Alan Shearer', team: 'Newcastle United' },
      { num: 'PK-13', name: 'Thierry Henry', team: 'Arsenal' },
      { num: 'PK-14', name: 'Wayne Rooney', team: 'Manchester United' },
      { num: 'PK-15', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'PK-16', name: 'Frank Lampard', team: 'Chelsea' },
      { num: 'PK-17', name: 'Steven Gerrard', team: 'Liverpool FC' },
      { num: 'PK-18', name: 'Paul Scholes', team: 'Manchester United' },
      { num: 'PK-19', name: 'Dennis Bergkamp', team: 'Arsenal' },
      { num: 'PK-20', name: 'Sergio Agüero', team: 'Manchester City' },
    ],
    'Headliners': [
      { num: 'HS-1', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'HS-2', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'HS-3', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'HS-4', name: 'Martin Ødegaard', team: 'Arsenal' },
      { num: 'HS-5', name: 'Rodri', team: 'Manchester City' },
      { num: 'HS-6', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'HS-7', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'HS-8', name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 'HS-9', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'HS-10', name: 'Morgan Gibbs-White', team: 'Nottingham Forest' },
    ],
    'Aura': [
      { num: 'AU-1', name: 'Mario Balotelli', team: 'Manchester City' },
      { num: 'AU-2', name: 'Gianfranco Zola', team: 'Chelsea' },
      { num: 'AU-3', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'AU-4', name: 'Paul Gascoigne', team: 'Everton' },
      { num: 'AU-5', name: 'Jack Grealish', team: 'Everton' },
      { num: 'AU-6', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'AU-7', name: 'Fernandinho', team: 'Manchester City' },
      { num: 'AU-8', name: 'Claude Makélélé', team: 'Chelsea' },
      { num: 'AU-9', name: 'Roy Keane', team: 'Manchester United' },
      { num: 'AU-10', name: 'William Saliba', team: 'Arsenal' },
      { num: 'AU-11', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'AU-12', name: 'Wayne Rooney', team: 'Manchester United' },
      { num: 'AU-13', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'AU-14', name: 'Steven Gerrard', team: 'Liverpool FC' },
      { num: 'AU-15', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'AU-16', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'AU-17', name: 'Florian Wirtz', team: 'Liverpool FC' },
      { num: 'AU-18', name: 'Thierry Henry', team: 'Arsenal' },
      { num: 'AU-19', name: 'Harry Kane', team: 'Tottenham Hotspur' },
      { num: 'AU-20', name: 'Didier Drogba', team: 'Chelsea' },
    ],
    'Finest Idols': [
      { num: 'FI-1', name: 'Steven Gerrard', team: 'Liverpool FC' },
      { num: 'FI-2', name: 'Frank Lampard', team: 'Chelsea' },
      { num: 'FI-3', name: 'Sergio Agüero', team: 'Manchester City' },
      { num: 'FI-4', name: 'Harry Kane', team: 'Tottenham Hotspur' },
      { num: 'FI-5', name: 'Wayne Rooney', team: 'Manchester United' },
    ],
    'Finest Autographs': [
      { num: 'FA-AC', name: 'Alfie Cresswell', team: 'Leeds United', isRookie: true },
      { num: 'FA-AE', name: 'Anthony Elanga', team: 'Newcastle United' },
      { num: 'FA-AG', name: 'Archie Gray', team: 'Tottenham Hotspur' },
      { num: 'FA-AI', name: 'Alexander Isak', team: 'Liverpool FC' },
      { num: 'FA-AN', name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 'FA-AR', name: 'Antonee Robinson', team: 'Fulham' },
      { num: 'FA-AY', name: 'Ashley Young', team: 'Aston Villa' },
      { num: 'FA-BE', name: 'Bendito Mantato', team: 'Manchester United', isRookie: true },
      { num: 'FA-BF', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'FA-BG', name: 'Brajan Gruda', team: 'Brighton & Hove Albion' },
      { num: 'FA-BM', name: 'Bryan Mbeumo', team: 'Manchester United' },
      { num: 'FA-BO', name: 'Jarrod Bowen', team: 'West Ham United' },
      { num: 'FA-BS', name: 'Bukayo Saka', team: 'Arsenal' },
      { num: 'FA-CA', name: 'Santi Cazorla', team: 'Arsenal' },
      { num: 'FA-CD', name: 'Clint Dempsey', team: 'Fulham' },
      { num: 'FA-CG', name: 'Cody Gakpo', team: 'Liverpool FC' },
      { num: 'FA-CH', name: 'Callum Hudson-Odoi', team: 'Nottingham Forest' },
      { num: 'FA-CP', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'FA-CR', name: 'Chris Richards', team: 'Crystal Palace' },
      { num: 'FA-CW', name: 'Chris Wood', team: 'Nottingham Forest' },
      { num: 'FA-DD', name: 'Diogo Dalot', team: 'Manchester United' },
      { num: 'FA-DI', name: 'Denis Irwin', team: 'Manchester United' },
      { num: 'FA-DK', name: 'Dirk Kuyt', team: 'Liverpool FC' },
      { num: 'FA-DL', name: 'David Luiz', team: 'Chelsea' },
      { num: 'FA-DM', name: 'Divine Mukasa', team: 'Manchester City', isRookie: true },
      { num: 'FA-DO', name: 'Dango Ouattara', team: 'Brentford' },
      { num: 'FA-DR', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'FA-DS', name: 'Dominic Solanke', team: 'Tottenham Hotspur' },
      { num: 'FA-EA', name: 'Emmanuel Adebayor', team: 'Arsenal' },
      { num: 'FA-EF', name: 'Enzo Fernández', team: 'Chelsea' },
      { num: 'FA-EH', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'FA-EM', name: 'El Hadji Malick Diouf', team: 'West Ham United', isRookie: true },
      { num: 'FA-EN', name: 'Ethan Nwaneri', team: 'Arsenal' },
      { num: 'FA-ES', name: 'Emile Smith Rowe', team: 'Fulham' },
      { num: 'FA-EW', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'FA-GI', name: 'Jamie Gittens', team: 'Chelsea' },
      { num: 'FA-GU', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'FA-GX', name: 'Granit Xhaka', team: 'Sunderland' },
      { num: 'FA-HG', name: 'Harry Gray', team: 'Leeds United', isRookie: true },
      { num: 'FA-IB', name: 'Amir Ibragimov', team: 'Manchester United', isRookie: true },
      { num: 'FA-IN', name: 'Iliman Ndiaye', team: 'Everton' },
      { num: 'FA-JB', name: 'Jayden Bogle', team: 'Leeds United' },
      { num: 'FA-JG', name: 'Jack Grealish', team: 'Everton' },
      { num: 'FA-JM', name: 'John McGinn', team: 'Aston Villa' },
      { num: 'FA-JO', name: 'João Palhinha', team: 'Tottenham Hotspur' },
      { num: 'FA-JR', name: 'Jacob Ramsey', team: 'Newcastle United' },
      { num: 'FA-JS', name: 'Jørgen Strand Larsen', team: 'Wolverhampton Wanderers' },
      { num: 'FA-JZ', name: 'Joshua Zirkzee', team: 'Manchester United' },
      { num: 'FA-KS', name: 'Kevin Schade', team: 'Brentford' },
      { num: 'FA-KW', name: 'Kyle Walker', team: 'Burnley FC' },
      { num: 'FA-LD', name: 'Liam Delap', team: 'Chelsea' },
      { num: 'FA-LP', name: 'Lucas Paquetá', team: 'West Ham United' },
      { num: 'FA-LS', name: 'Leroy Sané', team: 'Manchester City' },
      { num: 'FA-MC', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'FA-MD', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'FA-MG', name: 'Marc Guiu', team: 'Chelsea' },
      { num: 'FA-MI', name: 'Milos Kerkez', team: 'Liverpool FC' },
      { num: 'FA-MK', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'FA-ML', name: 'Myles Lewis-Skelly', team: 'Arsenal' },
      { num: 'FA-MS', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'FA-MZ', name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 'FA-NC', name: 'Nathan Collins', team: 'Brentford' },
      { num: 'FA-NM', name: 'Noni Madueke', team: 'Arsenal' },
      { num: 'FA-NV', name: 'Nemanja Vidić', team: 'Manchester United' },
      { num: 'FA-NW', name: 'Nick Woltemade', team: 'Newcastle United' },
      { num: 'FA-OG', name: 'Olivier Giroud', team: 'Arsenal' },
      { num: 'FA-OM', name: 'Omar Marmoush', team: 'Manchester City' },
      { num: 'FA-OW', name: 'Ollie Watkins', team: 'Aston Villa' },
      { num: 'FA-PE', name: 'João Pedro', team: 'Chelsea' },
      { num: 'FA-PF', name: 'Phil Foden', team: 'Manchester City' },
      { num: 'FA-PN', name: 'Pedro Neto', team: 'Chelsea' },
      { num: 'FA-RG', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'FA-RI', name: 'John Arne Riise', team: 'Liverpool FC' },
      { num: 'FA-RM', name: 'Riyad Mahrez', team: 'Manchester City' },
      { num: 'FA-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'FA-RW', name: 'Reggie Walsh', team: 'Chelsea', isRookie: true },
      { num: 'FA-SA', name: 'Simon Adingra', team: 'Sunderland' },
      { num: 'FA-SC', name: 'Sol Campbell', team: 'Arsenal' },
      { num: 'FA-SL', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'FA-SM', name: 'Shumaira Mheuka', team: 'Chelsea', isRookie: true },
      { num: 'FA-TD', name: 'Tyler Dibling', team: 'Everton' },
      { num: 'FA-TO', name: 'Sandro Tonali', team: 'Newcastle United' },
      { num: 'FA-TR', name: 'Tijjani Reijnders', team: 'Manchester City' },
      { num: 'FA-TW', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'FA-VD', name: 'Virgil van Dijk', team: 'Liverpool FC' },
      { num: 'FA-VG', name: 'Viktor Gyökeres', team: 'Arsenal' },
      { num: 'FA-WS', name: 'William Saliba', team: 'Arsenal' },
      { num: 'FA-YA', name: 'Yasin Ayari', team: 'Brighton & Hove Albion', isRookie: true },
      { num: 'FA-YY', name: 'Yehor Yarmolyuk', team: 'Brentford' },
    ],
    'Finest Moments Autographs': [
      { num: 'FM-AS', name: 'Alan Shearer', team: 'Newcastle United' },
      { num: 'FM-AY', name: 'Ashley Young', team: 'Aston Villa' },
      { num: 'FM-BM', name: 'David Beckham', team: 'Manchester United' },
      { num: 'FM-CT', name: 'Carlos Tevez', team: 'West Ham United' },
      { num: 'FM-DB', name: 'Dennis Bergkamp', team: 'Arsenal' },
      { num: 'FM-DJ', name: 'David James', team: 'Manchester City' },
      { num: 'FM-EH', name: 'Erling Haaland', team: 'Manchester City' },
      { num: 'FM-HS', name: 'Heung-Min Son', team: 'Tottenham Hotspur' },
      { num: 'FM-HZ', name: 'Eden Hazard', team: 'Chelsea' },
      { num: 'FM-IW', name: 'Ian Wright', team: 'Arsenal' },
      { num: 'FM-JH', name: 'Jordan Henderson', team: 'Sunderland' },
      { num: 'FM-JM', name: 'José Mourinho', team: 'Chelsea' },
      { num: 'FM-KK', name: 'Kevin Keegan', team: 'Newcastle United' },
      { num: 'FM-LS', name: 'Lee Sharpe', team: 'Manchester United' },
      { num: 'FM-ME', name: 'Michael Essien', team: 'Chelsea' },
      { num: 'FM-OG', name: 'Olivier Giroud', team: 'Arsenal' },
      { num: 'FM-PC', name: 'Papiss Cissé', team: 'Newcastle United' },
      { num: 'FM-PG', name: 'Pep Guardiola', team: 'Manchester City' },
      { num: 'FM-PV', name: 'Patrick Vieira', team: 'Arsenal' },
      { num: 'FM-RK', name: 'Roy Keane', team: 'Manchester United' },
      { num: 'FM-SA', name: 'Sergio Agüero', team: 'Manchester City' },
      { num: 'FM-SB', name: 'Steve Bruce', team: 'Manchester United' },
      { num: 'FM-TA', name: 'Tony Adams', team: 'Arsenal' },
      { num: 'FM-WR', name: 'Wayne Rooney', team: 'Everton' },
    ],
    'Finest Seasons 1995-96': [
      { num: 'FS-AK', name: 'Andrei Kanchelskis', team: 'Everton' },
      { num: 'FS-DJ', name: 'David James', team: 'Liverpool FC' },
      { num: 'FS-DY', name: 'Dwight Yorke', team: 'Aston Villa' },
      { num: 'FS-EC', name: 'Eric Cantona', team: 'Manchester United' },
      { num: 'FS-GN', name: 'Gary Neville', team: 'Manchester United' },
      { num: 'FS-IW', name: 'Ian Wright', team: 'Arsenal' },
      { num: 'FS-LF', name: 'Les Ferdinand', team: 'Newcastle United' },
      { num: 'FS-PS', name: 'Peter Schmeichel', team: 'Manchester United' },
      { num: 'FS-RF', name: 'Robbie Fowler', team: 'Liverpool FC' },
      { num: 'FS-RG', name: 'Ruud Gullit', team: 'Chelsea' },
      { num: 'FS-RL', name: 'Rob Lee', team: 'Newcastle United' },
      { num: 'FS-SC', name: 'Stan Collymore', team: 'Liverpool FC' },
      { num: 'FS-SS', name: 'Steve Stone', team: 'Nottingham Forest' },
      { num: 'FS-TA', name: 'Tony Adams', team: 'Arsenal' },
      { num: 'FS-TS', name: 'Teddy Sheringham', team: 'Tottenham Hotspur' },
    ],
    'Finest Partnerships': [
      { num: 'FP-AS', name: 'Darren Anderton & Teddy Sheringham', team: 'Tottenham Hotspur' },
      { num: 'FP-CY', name: 'Dwight Yorke & Andy Cole', team: 'Manchester United' },
      { num: 'FP-DK', name: 'Robbie Keane & Jermain Defoe', team: 'Tottenham Hotspur' },
      { num: 'FP-DL', name: 'Didier Drogba & Frank Lampard', team: 'Chelsea' },
      { num: 'FP-GH', name: 'Jimmy Floyd Hasselbaink & Eiður Guðjohnsen', team: 'Chelsea' },
      { num: 'FP-HB', name: 'Thierry Henry & Dennis Bergkamp', team: 'Arsenal' },
      { num: 'FP-HP', name: 'Thierry Henry & Robert Pirès', team: 'Arsenal' },
      { num: 'FP-KS', name: 'Heung-Min Son & Harry Kane', team: 'Tottenham Hotspur' },
      { num: 'FP-MS', name: 'Gabriel Magalhães & William Saliba', team: 'Arsenal' },
      { num: 'FP-PQ', name: 'Niall Quinn & Kevin Phillips', team: 'Sunderland' },
      { num: 'FP-SF', name: 'Alan Shearer & Les Ferdinand', team: 'Newcastle United' },
      { num: 'FP-SM', name: 'Sadio Mané & Mohamed Salah', team: 'Liverpool FC' },
      { num: 'FP-SS', name: 'Luis Suárez & Daniel Sturridge', team: 'Liverpool FC' },
      { num: 'FP-TC', name: 'John Terry & Ricardo Carvalho', team: 'Chelsea' },
      { num: 'FP-ZP', name: 'Gustavo Poyet & Gianfranco Zola', team: 'Chelsea' },
    ],
    'Arrivals Autograph Edition': [
      { num: 'AA-AI', name: 'Amir Ibragimov', team: 'Manchester United', isRookie: true },
      { num: 'AA-BB', name: 'Ben Broggio', team: 'Aston Villa', isRookie: true },
      { num: 'AA-BM', name: 'Bendito Mantato', team: 'Manchester United', isRookie: true },
      { num: 'AA-CR', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'AA-EW', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'AA-JK', name: 'Josh King', team: 'Fulham', isRookie: true },
      { num: 'AA-MD', name: 'Max Dowman', team: 'Arsenal', isRookie: true },
      { num: 'AA-RD', name: 'Romelle Donovan', team: 'Brentford', isRookie: true },
      { num: 'AA-RN', name: 'Rio Ngumoha', team: 'Liverpool FC', isRookie: true },
      { num: 'AA-SL', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'AA-TW', name: 'Tom Watson', team: 'Brighton & Hove Albion', isRookie: true },
    ],
    'Main Attraction Autograph Edition': [
      { num: 'MA-AC', name: 'Andy Cole', team: 'Manchester United' },
      { num: 'MA-BF', name: 'Bruno Fernandes', team: 'Manchester United' },
      { num: 'MA-CP', name: 'Cole Palmer', team: 'Chelsea' },
      { num: 'MA-CT', name: 'Carlos Tevez', team: 'Manchester City' },
      { num: 'MA-DS', name: 'David Silva', team: 'Manchester City' },
      { num: 'MA-EW', name: 'Estêvão Willian', team: 'Chelsea', isRookie: true },
      { num: 'MA-GB', name: 'Gareth Bale', team: 'Tottenham Hotspur' },
      { num: 'MA-JG', name: 'Jack Grealish', team: 'Everton' },
      { num: 'MA-LM', name: 'Luka Modrić', team: 'Tottenham Hotspur' },
      { num: 'MA-MC', name: 'Matheus Cunha', team: 'Manchester United' },
      { num: 'MA-MO', name: 'Moisés Caicedo', team: 'Chelsea' },
      { num: 'MA-MR', name: 'Morgan Rogers', team: 'Aston Villa' },
      { num: 'MA-MS', name: 'Mohamed Salah', team: 'Liverpool FC' },
      { num: 'MA-MZ', name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 'MA-RO', name: 'Rodri', team: 'Manchester City' },
      { num: 'MA-VD', name: 'Virgil van Dijk', team: 'Liverpool FC' },
    ],
    'Gustographs': [
      { num: 'GG-AG', name: 'Anthony Gordon', team: 'Newcastle United' },
      { num: 'GG-BG', name: 'Bruno Guimarães', team: 'Newcastle United' },
      { num: 'GG-BS', name: 'Benjamin Šeško', team: 'Manchester United' },
      { num: 'GG-CR', name: 'Chris Rigg', team: 'Sunderland', isRookie: true },
      { num: 'GG-DR', name: 'Declan Rice', team: 'Arsenal' },
      { num: 'GG-DS', name: 'Dominik Szoboszlai', team: 'Liverpool FC' },
      { num: 'GG-EF', name: 'Enzo Fernández', team: 'Chelsea' },
      { num: 'GG-HE', name: 'Hugo Ekitike', team: 'Liverpool FC' },
      { num: 'GG-JB', name: 'Jarrod Bowen', team: 'West Ham United' },
      { num: 'GG-JP', name: 'João Pedro', team: 'Chelsea' },
      { num: 'GG-KH', name: 'Kai Havertz', team: 'Arsenal' },
      { num: 'GG-MK', name: 'Mohammed Kudus', team: 'Tottenham Hotspur' },
      { num: 'GG-MZ', name: 'Martín Zubimendi', team: 'Arsenal' },
      { num: 'GG-SL', name: 'Shea Lacey', team: 'Manchester United', isRookie: true },
      { num: 'GG-TR', name: 'Tijjani Reijnders', team: 'Manchester City' },
    ],
    'Finest Fans': [
      { num: 'FF-AH', name: 'Anne Hathaway', team: 'Arsenal' },
      { num: 'FF-CT', name: 'Charlize Theron', team: '—' },
      { num: 'FF-JM', name: 'Joe Marler', team: 'Brighton & Hove Albion' },
      { num: 'FF-JS', name: 'Jill Scott', team: 'Sunderland' },
      { num: 'FF-LBJ', name: 'LeBron James', team: 'Liverpool FC' },
      { num: 'FF-LW', name: 'Laura Woods', team: 'Arsenal' },
      { num: 'FF-MB', name: 'Mel B', team: 'Leeds United' },
      { num: 'FF-MBB', name: 'Millie Bobby Brown', team: 'Liverpool FC' },
      { num: 'FF-MC', name: 'Mel C', team: 'Liverpool FC' },
      { num: 'FF-RI', name: 'Ralph Ineson', team: 'Leeds United' },
      { num: 'FF-SB', name: 'Stuart Broad', team: 'Nottingham Forest' },
      { num: 'FF-SLJ', name: 'Samuel L. Jackson', team: 'Liverpool FC' },
    ],
  },
};